### ISSUE TITLE
Separate parameters' properties and effect size one (and link significance to direction)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#102]
Currently, it's like this:

`The effect of Species [versicolor] is positive and can be considered as large and significant (beta = 0.93, SE = 0.10, 95% CI [0.73, 1.13], std. beta = 1.12, p < .001).`

It includes interpretation of direction, "significance" and size and after that all the values are included.

I wonder whether 1) we should link significance to direction (and it would also bridge Bayesian and frequentist models), as the p-value and the CI is quite tied to the certainty surrounding the direction.

Something like `The effect of x is significantly positive (...)`

It would be also easier down the road to replace "significance" by something a more appropriate adjective (see #73). I'm just worried that it sounds weird at first.

And 2) whether we could dissociate effect size interpretation and indices, like:

`The effect of x is significantly positive (...) and can be considered as large (metrics of effectsize)`

This would IMO be clearer regarding the link between the verbal interpretation and the numeric index it is based on, and it would leave room to add CI or multiple indices of effect size (as it would have its own separate brackets). For instance,

`The effect of Species [versicolor] is significantly positive (beta = 0.93, SE = 0.10, 95% CI [0.73, 1.13], p < .001) and can be considered as large (std. beta = 1.12, 95% CI [1.00, 2.00]).`

My only worry is that it's too verbose. 

what y'all think?

**Comment by mattansb** [comment]
I like "significantly positive", that ti s nicely with what NHST does.

And it won't be as verbose once the regression interpretation is dropped, as discussed (:

**Comment by strengejacke** [comment]
We could probably include different templates for text output?

**Comment by DominiqueMakowski** [comment]
> We could probably include different templates for text output?

we could, tho having a good default one is a good first step :)

**Comment by DominiqueMakowski** [comment]
> once the regression interpretation is dropped, as discussed (:

![](https://i.kym-cdn.com/entries/icons/original/000/030/710/dd0.png)

**Comment by DominiqueMakowski** [comment]
I removed effectsize interpretation entirely for now 🤷‍♂️

**Comment by mattansb** [comment]
🙌
