### ISSUE TITLE
NAMESPACE - Requiring package version in dependencies which is not yet existing.

### ISSUE THREAD

**Issue by kgryczan** [easystats/report#106]
I think that I found a problem in DESCRIPTION file. 
I am trying to install this package, but there is "insight" package in dependencies. 
As far as i found out its latest version is 0.10.0.1. Using function easystats::install_easystats_latest() is also installing this version, but when trying to install "report" package there is an error "namespace 'insight' 0.10.0.1 is already loaded, but >= 0.10.1 is required". I checked DESCRIPTION file and in 34th line in "Imports" section there is something like this: "insight (>= 0.10.1),". This could be the source of problem.

**Comment by DominiqueMakowski** [comment]
Indeed @kgryczan, thanks for the report!

**Comment by DominiqueMakowski** [comment]
(it should be fixed now)

**Comment by strengejacke** [comment]
I corrected the insight-version, because 0.10.1 could be a potential next version number on CRAN, so I lowered to 0.10.0.1, which also indicates a current dev-version.

**Comment by DominiqueMakowski** [comment]
right so it's all @strengejacke's fault as always 🤷‍♂️
