### ISSUE TITLE
Error in report() function for gamma/inverse gaussian family GLMM

### ISSUE THREAD

**Issue by courtneygoodridge** [easystats/report#107]
I am modelling some reaction time data using the glmer() function from the lme4 package. I am specifying gamma and inverse gaussian families with identity link function: 

`fit.gamma.rt <- glmer(FirstSteeringTime ~ heading + (1 + heading | pNum),
              family = Gamma(link = "identity"),
              data = magnitudedata)`

`fit.invgauss.rt <- glmer(FirstSteeringTime ~ heading + (1 + heading | pNum),
              family = inverse.gaussian(link = "identity"),
              data = magnitudedata)`

When I use the report function on these models, I get the following error:

`report(fit.gamma.rt)`
`report(fit.invgauss.rt)`

`Error in eval(family$initialize, rho) : 
  non-positive values not allowed for the 'Gamma' family`
`Error in eval(family$initialize, rho) : 
  positive values only are allowed for the 'inverse.gaussian' family`

However my reaction time data and fixed/random effect variables are definitely all positive values. A possible bug?

My R/package versions are as follows:

`R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)`
`report_0.2.0`
`lme4_1.1-23`

**Comment by mattansb** [comment]
It seems report is refitting the model with standardized data (via `effectsize::standardize_parameters(model, method = "refit")`), and is also standardizing the response, though it shouldn't for such models. Which is happening here:

https://github.com/easystats/effectsize/blob/master/R/standardize.models.R#L21

@DominiqueMakowski can you confirm? (and also address this in `effectisze`? I'm not sure how to "catch" Gamma / inv-gaus, or what the appropriate standardization should be? (only scale, without centering? nothing?))

**Comment by DominiqueMakowski** [comment]
``` r
model <- lme4::glmer(Sepal.Length ~ Sepal.Width + (1 | Species), family = Gamma(link = "identity"), data = iris)
effectsize::standardize(model)
#> Error in eval(family$initialize, rho): non-positive values not allowed for the 'Gamma' family
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Indeed. But isn't it de standardization type by default "refit"?

**Comment by mattansb** [comment]
It is - which is what is causing the problem (:

**Comment by mattansb** [comment]
I think in this case, the response should prob be treated the same as other "log terms":
https://github.com/easystats/effectsize/blob/master/R/standardize.models.R#L74

No?

**Comment by DominiqueMakowski** [comment]
ah yes yes indeed. Mmh then I guess for all General models we should not modify the outcome variable (only standardize it for lmer - not for glmer). I think we can catch it via insight::model_info(model)$is_linear to see if it's linear or not, in which case we skil the outcome

**Comment by mattansb** [comment]
Not sure - if in Courtney's example he used RTs in S or in MS, not standardizing at all would give different results.

So perhaps for Gamma and inv-gauss (and maybe others?) we should do the same `z - min(z) + 1`, like for exponential predictors?
Maybe @strengejacke has any thoughts?

**Comment by strengejacke** [comment]
Since the Gamma distribution may vary between normal to exponential, and Gamma regression requires positive values, we may consider adding it to the "no response standardization" list:

https://github.com/easystats/effectsize/blob/d14cdd468a04e8a4ad6dcb59361a025714f980bc/R/standardize.models.R#L227

We probably wouldn't find a good denominator for standardization, anyway (e.g. mean/mad/...), or?

**Comment by strengejacke** [comment]
The check would be `model_info()$is_exponential`.

**Comment by strengejacke** [comment]
I don't know all those possible exceptions, but maybe it's indeed easier to just allow `model_info()$is_linear` for response standardization?

**Comment by mattansb** [comment]
If model is linear and if link is identity...?

**Comment by strengejacke** [comment]
That would be no problem, the inverse Gaussian may cause troubles, so I would now check how to catch this inside `model_info()`.
