### ISSUE TITLE
Trouble installing report package

### ISSUE THREAD

**Issue by clairedonnici** [easystats/report#110]
I have been attempting to install your package in RStudio on OSX. Here is the issue I keep getting 

![img](https://i.imgur.com/dvafVh2.png)

Below is my `sessionInfo()`

<img width="1110" alt="Screen Shot 2020-11-09 at 11 44 25 AM" src="https://user-images.githubusercontent.com/74207225/98582901-cfa83e00-2280-11eb-82bb-6f83b9e1fe24.png">

**Comment by DominiqueMakowski** [comment]
Hi @clairedonnici welcome to github. I am not exactly sure what is going on, but could you try running the following command and giving us the error log? we'll look into it ☺️ 

```r
library(remotes)
remotes::install_github("easystats/insight")
remotes::install_github("easystats/bayestestR")
remotes::install_github("easystats/parameters")
remotes::install_github("easystats/effectsize")
remotes::install_github("easystats/performance")
remotes::install_github("easystats/report")
````

**Comment by clairedonnici** [comment]
Hi @DominiqueMakowski thank you for your reply. I have now solved the issue - it was related to the version of software I was using.
