### ISSUE TITLE
Error in if (attributes(table)$bootstrap) { : argument is of length zero

### ISSUE THREAD

**Issue by CJkirk105** [easystats/report#112]
I've just tried to run report on my model that was created using the 'lm' function, and I'm getting the error message: 

Error in if (attributes(table)$bootstrap) { : argument is of length zero

Report was working perfectly fine on these models before, so I'm unsure what's causing the problem, if someone could please help that would be appreciated! 

Thanks 

Cam

**Comment by strengejacke** [comment]
Do you have a reproducible example?
