### ISSUE TITLE
model_text fails with lm-model - "formal argument "standardize" matched by multiple actual arguments"

### ISSUE THREAD

**Issue by LukasWallrich** [easystats/report#115]
I am trying to use report_text, but it fails already when I try to run the example from the documentation. Would be great if that could be fixed?

``` r
library(report)
model <- lm(Sepal.Length ~ Petal.Length * Species, data = iris)
model_text(model)
#> Error in model_parameters.default(model, ci = ci, standardize = NULL, : formal argument "standardize" matched by multiple actual arguments
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Hi @LukasWallrich sorry for the delayed repsonse! I'll look into it now  ☺️

**Comment by strengejacke** [comment]
@DominiqueMakowski you may look at this PR: https://github.com/easystats/parameters/pull/357

I think you can solve this issue by capturing the dots, filter out arguments that appear multiple times save then use `do.call()` with the remaining arguments as list.

**Comment by DominiqueMakowski** [comment]
``` r
m <- lm(Sepal.Length ~ Petal.Width, data=iris)
effectsize::effectsize(m, standardize=T)
#> Error in model_parameters.default(model, ci = ci, standardize = NULL, : formal argument "standardize" matched by multiple actual arguments
```

<sup>Created on 2020-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


I think it might fail because in `report_effecsize()` (the first thing that's run) it is passed to effectsize:

https://github.com/easystats/report/blob/5fdc5296e2b287ea68dfa8793d9e132db470bac6/R/report.lm.R#L66-L67

At what level should it be dealt with?

**Comment by strengejacke** [comment]
I think that might be the best place, i.e. don't pass it down to effectsize.

**Comment by DominiqueMakowski** [comment]
how so 🤔

**Comment by strengejacke** [comment]
https://github.com/easystats/report/issues/115#issuecomment-742361547

**Comment by strengejacke** [comment]
`do.call()`, your underestimated friend when dealing with `...` arguments 😬

**Comment by mattansb** [comment]
```R
table <- suppressWarnings(effectsize::effectsize(x, method = effectsize_method, ...)) 
```

What `method` argument is this? 🤔

**Comment by strengejacke** [comment]
> how so 🤔

A short version would be:

1. Get dots via `dot_args <- list(...)`. The names of the elements are the argument names
2. Add further necessary arguments to the list `dot_args` (make sure you add no duplicated)
2. call `do.call(effectsize::effectsize, dot_args)`

A more "safe" version would be

1. Get dots via `dot_args <- list(...)`. The names of the elements are the argument names
2. Find all defined arguments of `model_parameters()` (like `standardized` etc.) in the names of `dot_args`, _which are not used for the call to `effectsize::effectsize()`_, and remove them from the list `dot_args`.
3. Add further necessary arguments to the list `dot_args` (make sure you add no duplicated)
4. call `do.call(effectsize::effectsize, dot_args)`

**Comment by strengejacke** [comment]
I think due to the code-rewrite, this bug no longer exists.
