### ISSUE TITLE
Unclear that kurtosis is in fact excess kurtosis

### ISSUE THREAD

**Issue by msberends** [easystats/report#116]
Many thanks for your great ecosystem of easystats packages. 

I just find it unclear from this ‘reports’ pkg that the kurtosis is in fact the excess kurtosis (kurtosis minus 3). In the code I see that you use the ‘parameters’ package for the calculation of the kurtosis and use type = “1”. 

Obvious choice, but in the output of ‘reports’ functions and in the ‘reports’ documentation of this package not clear that you rely on that package, function and type. And thus that you’re presenting the excess kurtosis :)

**Comment by DominiqueMakowski** [comment]
Nice catch, thanks! 
I added a link in report's docs linking to the `kurtosis()` from parameters, and removed the hard-coding of the type (I don't remember why it was there).

**Comment by msberends** [comment]
Awesome!
