### ISSUE TITLE
Error when calling report_table() on lm object.

### ISSUE THREAD

**Issue by mscharkow** [easystats/report#119]
I use easystats for teaching data visualization, and one of my students gets an error message when calling report_table() on after an lm call:
library(report)
m1 = lm(mpg~cyl, mtcars)
report_table(m1)

yields: Fehler in cat(insight::format_table(format(x, ...), ...)) : Argument 1 (Typ 'list') wird nicht von 'cat' beherrscht

Unfortunately, I cannot reproduce the error on my Mac, even though we both have are up-to-date after calling easystats_upgrade().
Maybe you have an idea what might cause this.

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

 

Matrix products: default

 

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

 

other attached packages:
[1] report_0.2.0

 

loaded via a namespace (and not attached):
 [1] compiler_4.0.3      prettyunits_1.1.1   parameters_0.10.1.1 easystats_0.2.0    
 [5] remotes_2.2.0       tools_4.0.3         testthat_3.0.0      digest_0.6.27      
 [9] pkgbuild_1.1.0      pkgload_1.1.0       memoise_1.1.0       lifecycle_0.2.0    
[13] rlang_0.4.8         cli_2.1.0           rstudioapi_0.11     xfun_0.19          
[17] xml2_1.3.2          httr_1.4.2          bayestestR_0.8.0.1  withr_2.3.0        
[21] desc_1.2.0          fs_1.5.0            devtools_2.3.2      rprojroot_2.0.2    
[25] glue_1.4.2          performance_0.6.1.1 R6_2.5.0            processx_3.4.4     
[29] fansi_0.4.1         sessioninfo_1.1.1   purrr_0.3.4         callr_3.5.1        
[33] magrittr_1.5        ps_1.4.0            ellipsis_0.3.1      usethis_2.0.0      
[37] rvest_0.3.6         assertthat_0.2.1    insight_0.11.1.1    effectsize_0.4.1.2 
[41] tinytex_0.27        crayon_1.3.4

**Comment by DominiqueMakowski** [comment]
``` r
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
m1 = lm(mpg~cyl, mtcars)
report_table(m1)
#> Error in cat(insight::format_table(format(x, ...), ...)): argument 1 (type 'list') cannot be handled by 'cat'
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Actually I think I have the same error 😱

**Comment by DominiqueMakowski** [comment]
Could be related to the latest insight printing... but weird we haven't caught that earlier!

**Comment by DominiqueMakowski** [comment]
``` r
cat(iris)
#> Error in cat(iris): argument 1 (type 'list') cannot be handled by 'cat'
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I have the same error if I `cat()` a dataframe (which is what happens upon printing of the report table). Is it just me or is a new behaviour ❓

**Comment by DominiqueMakowski** [comment]
@mscharkow as a quick fix, you can force the output to a regular dataframe:

``` r
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
m1 = lm(mpg~cyl, mtcars)
as.data.frame(report_table(m1))
#>     Parameter Coefficient    CI_low   CI_high         t df_error            p
#> 1 (Intercept)    37.88458 33.649223 42.119930 18.267808       30 8.369155e-18
#> 2         cyl    -2.87579 -3.534237 -2.217343 -8.919699       30 6.112687e-10
#> 3        <NA>          NA        NA        NA        NA       NA           NA
#> 4         AIC          NA        NA        NA        NA       NA           NA
#> 5         BIC          NA        NA        NA        NA       NA           NA
#> 6          R2          NA        NA        NA        NA       NA           NA
#> 7   R2 (adj.)          NA        NA        NA        NA       NA           NA
#> 9       Sigma          NA        NA        NA        NA       NA           NA
#>   Std_Coefficient Std_Coefficient_CI_low Std_Coefficient_CI_high         Fit
#> 1    8.533404e-18             -0.1920399               0.1920399          NA
#> 2   -8.521620e-01             -1.0472747              -0.6570492          NA
#> 3              NA                     NA                      NA          NA
#> 4              NA                     NA                      NA 169.3064172
#> 5              NA                     NA                      NA 173.7036249
#> 6              NA                     NA                      NA   0.7261800
#> 7              NA                     NA                      NA   0.7170527
#> 9              NA                     NA                      NA   3.2059020
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
`format_table()` is now `export_table()` <sup>(because former `parameters_table()` is now `format_table()`)</sup>

**Comment by strengejacke** [comment]
``` r
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
m1 = lm(mpg~cyl, mtcars)
report_table(m1)
#> Parameter   | Coefficient |         95% CI |     t | df |      p | Std. Coef. | Std. Coef. 95% CI |    Fit
#> ----------------------------------------------------------------------------------------------------------
#> (Intercept) |       37.88 | [33.65, 42.12] | 18.27 | 30 | < .001 |   8.53e-18 |    [-0.19,  0.19] |       
#> cyl         |       -2.88 | [-3.53, -2.22] | -8.92 | 30 | < .001 |      -0.85 |    [-1.05, -0.66] |       
#>             |             |                |       |    |        |            |                   |       
#> AIC         |             |                |       |    |        |            |                   | 169.31
#> BIC         |             |                |       |    |        |            |                   | 173.70
#> R2          |             |                |       |    |        |            |                   |   0.73
#> R2 (adj.)   |             |                |       |    |        |            |                   |   0.72
#> Sigma       |             |                |       |    |        |            |                   |   3.21
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Should work now after `easystats::install_easystats_latest()`.
