### ISSUE TITLE
CRAN initial release

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#124]
It currently passes tests. Should we finally push it to CRAN to facilitate installing? What should we set as minimal versions for deps?

**Comment by strengejacke** [comment]
Yes, why not?

> What should we set as minimal versions for deps?

What do you mean? R or pkgs?

**Comment by DominiqueMakowski** [comment]
For pkgs, do We submit report after right this round of updates with the highest easystats thresholds?

**Comment by strengejacke** [comment]
Does it matter?

**Comment by DominiqueMakowski** [comment]
not really 😅

**Comment by DominiqueMakowski** [comment]
Alright should we try a first submission?

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/108673688-c324ba00-74ec-11eb-8e6d-950d20b4ac64.png)

**Comment by strengejacke** [comment]
_bump_

**Comment by IndrajeetPatil** [comment]
If you can wait for a couple of weeks, I can add support for a few robust tests from `WRS2`.

**Comment by DominiqueMakowski** [comment]
> If you can wait for a couple of weeks

Haha finally some *actual* reason to justify my delay

**Comment by IndrajeetPatil** [comment]
I think it would be wise to submit `report` to `CRAN` as part of this release cycle. 
I can work on adding support for non-parametric and robust methods in later releases.

Better not to risk losing a good package name...

**Comment by DominiqueMakowski** [comment]
Yes I think we can go ahead now with that since the other packages have been updated

**Comment by DominiqueMakowski** [comment]
Thanks,

Please omit the redundant "in R" from the title.

Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      cite_easystats.Rd: \arguments,  \value
      report.data.frame.Rd: \value


Some code lines in examples are commented out in
report.test_performance.Rd.
Please never do that. Ideally find toy examples that can be regularly
executed and checked. Lengthy examples (> 5 sec), can be wrapped in
\donttest.


\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
('# Not run:') as a warning for the user.
Does not seem necessary.

Please unwrap the examples if they are executable in < 5 sec, or replace
\dontrun{} with \donttest{}.


Please always make sure to reset to user's options(), working directory
or par() after you changed it in examples and vignettes and demos.
e.g.:
old <- options(digits = 3)
...
options(old)

Please fix and resubmit.

**Comment by DominiqueMakowski** [comment]
Thanks,
on its way to CRAN.

--- 

🎉

**Comment by strengejacke** [comment]
yay!

**Comment by strengejacke** [comment]
Best is this one here:
https://cran.r-project.org/web/packages/report/news/news.html

**Comment by IndrajeetPatil** [comment]
lmao 🤣

**Comment by mattansb** [comment]
Holy cow, you did it! 🤯🎉🍾

**Comment by DominiqueMakowski** [comment]
Yeah Im quite surprised myself haha it thought the "report on cran" question was going to stay around forever as a running gag 😅

**Comment by IndrajeetPatil** [comment]
Are you planning to write a blog post, or should I just expect to see fireworks in Singapore from here 😅

**Comment by DominiqueMakowski** [comment]
Haha! "Look to ~my coming~ the fireworks on the first light of the fifth day, at dawn look to the east"

 I'm actually leaning towards keeping this release low-key so that we have time to slowly fix some of the issues and bugs... Otherwise I'm worried that we'll be flooded à-la-check_model and that the amount of bugs will seem insurmountable...

...But it could be because I'm under the cooldown time after using the cran-release power (like all dungeons n dragons wizards 🧙‍♂️)... I must recover my mana before being able to commit again 🙃

**Comment by DominiqueMakowski** [comment]
But joke and personal cooldown aside yes, we should prolly advertise it :)

**Comment by mattansb** [comment]
I think keeping it low-key is a good idea.
Maybe we can spread it amongst friends and coworkers and get their response, make some fixes, and then advertise the next (more stable) release...
