### ISSUE TITLE
Cannot install from remotes

### ISSUE THREAD

**Issue by fab4ap** [easystats/report#125]
> remotes::install_github("easystats/report") 
Downloading GitHub repo easystats/report@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/easystats/report/tarball/HEAD'
Please resolve.
Thanks

**Comment by DominiqueMakowski** [comment]
This is probably related to reaching the limit of direct GitHub downloads; it seems like when they are too many queries github blocks new ones. O my thing I can recommend is try again in a few hours, and hopefully it should be resolved soon as we hope to publish the package on CRAN soon #124

**Comment by rbcavanaugh** [comment]
I am having this issue as well - but only for report, and not the other easystats packages.

**Comment by IndrajeetPatil** [comment]
@fab4ap Closing this for now. Please reopen if the issue persists.
