### ISSUE TITLE
Mispelled word in brm fit report

### ISSUE THREAD

**Issue by lucavd** [easystats/report#127]
**Describe the bug**
"successfully" is misspelled in `brm` fit

Maybe "0.95% CI" was intended as 95% CI?

**To Reproduce**
  - The effect of b_crisi_conv1 (Median = -0.29, **0.95% CI** [-1.15, 0.56]) has a 74.65% probability of being negative (< 0), 70.60% of being significant (< -0.05), and 47.80% of being large (< -0.32). The estimation **successfuly** converged (Rhat = 1.001) and the indices are reliable (ESS = 4615)

**Specifiations (please complete the following information):**
 - Package Version [e.g. 0.2.0]

**Comment by lucavd** [comment]
...moreover Rhat is spelled R-hat in the SEXIT explanation and Rhat in the model results description

**Comment by strengejacke** [comment]
Ok, I think everything should be addressed. Requires latest GitHub versions from _bayestestR_ and _report_.
