### ISSUE TITLE
cite_packages()

### ISSUE THREAD

**Issue by codingnewbie3** [easystats/report#142]
I just installed easystats/report and wanted to use the cite_packages() function at the end of a long rmarkdown file. When I use the cite_packages function, it will only cite the packages that in that code chunk, and none of the other chunks in the document. I am new to this, so I wasn't sure if I was just doing it wrong. 

If this is just how it works for now, it would be a useful tool to have it cite every package in the document.

**Comment by DominiqueMakowski** [comment]
That shouldn't be the case, `cite_packages()` uses the information from `sessionInfo()`, meaning that it will report all the packages loaded using `library(package)` at that point of time... unless you somehow manually clear the session from the packages?

**Comment by codingnewbie3** [comment]
I cleared my environment and re-ran my code. It works now! I will make sure to do that in the future. Sorry to bother you, and thanks for the quick reply!
