### ISSUE TITLE
report_table unction not working

### ISSUE THREAD

**Issue by Elif-print** [easystats/report#151]
Hello! I am using R 4.0.4 and tried to download the package report. This error came up **(1)**. The function "report" works however when I try to run "report_table", this error shows up **(2)**. ( Trying to report results for ANOVA )

1) **Warning in install.packages :
     package ‘report’ is not available for this version of R
    A version of this package for your version of R might be available elsewhere,
    see the ideas at
    https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages**

2)**Error: 'parameters_table' is not an exported object from 'namespace:parameters'**

**R version:**                           
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)

Thank you!

**Comment by IndrajeetPatil** [comment]
Hi,

Before we investigate this any further, can you please make sure that you are working with the most recent versions of `easystats` packages? It is possible that one of the dependencies for `report` is out of date and this is why you are getting this error.

1. Run `r easystats::install_easystats_dev()` (install all development versions of `easystats` packages)
2. Refresh R session
3. Try to run the code again

**Comment by DominiqueMakowski** [comment]
Should be working now that report is on CRAN
