### ISSUE TITLE
significance reporting issue: `"statistically NA"`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#167]
Need to figure out why there is `NA` in `"The main effect of cyl is statistically NA and large"`

``` r
library(report)

report(aov(wt ~ cyl + Error(gear), data = mtcars))
#> The repeated-measures ANOVA (formula: wt ~ cyl + Error(gear)) suggests that:
#> 
#>   - The main effect of cyl is statistically NA and large (F(1, 29) = 27.94, p < .001; Eta2 (partial) = 0.49, 90% CI [0.27, 0.64])
#>   - The main effect of cyl is statistically significant and large (F(1, 29) = 27.94, p < .001; Eta2 (partial) = 0.49, 90% CI [0.27, 0.64])
#> 
#> Effect sizes were labelled following Field's (2013) recommendations.
```

<sup>Created on 2021-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by humanfactors** [comment]
I have a few ideas that might help the debugging.

**In lines below, the `report_table` adds in an extra row (group) for the error on the gear variable.**

https://github.com/easystats/report/blob/55d93794666384e68e7e13f3a54d54755f24e9aa/R/report.aov.R#L223-L225

![image](https://user-images.githubusercontent.com/16096044/118616540-5facde80-b7f4-11eb-8b21-5dd70f8c84de.png)

**But the following test for the residuals only excludes on the basis of not being the residuals. So we get an output table still containing the second cyl parameter:**

https://github.com/easystats/report/blob/55d93794666384e68e7e13f3a54d54755f24e9aa/R/report.aov.R#L227

```
> params <- table[table$Parameter != "Residuals", ]
> params
Group  | Parameter | Sum_Squares | df | Mean_Square |     F |      p | Eta2 (partial) | Eta2_partial 90% CI
-----------------------------------------------------------------------------------------------------------
  gear   |       cyl |       10.10 |  1 |       10.10 |       |        |                |                    
  Within |       cyl |        9.61 |  1 |        9.61 | 27.94 | < .001 |           0.49 |        [0.27, 0.64]
```
**In turn, the sapply then creates two text objects**

```
  text <- sapply(params$Parameter, .format_parameters_aov, simplify = TRUE, USE.NAMES = FALSE)
> text
[1] "The main effect of cyl" "The main effect of cyl"
> length(text)
[1] 2
```

**And from there, it's a miracle all the logic still works as effectively as it does!**

**Comment by humanfactors** [comment]
The solution would be to adjust behavior of table creation (see below). However, I'm not sure on the expected behaviour/handling of the table for the Error term. Perhaps it would make sense to handle them with an "Error" group, to be excluded or dealt with later.

https://github.com/easystats/report/blob/55d93794666384e68e7e13f3a54d54755f24e9aa/R/report.aov.R#L110-L134

**Comment by humanfactors** [comment]
@DominiqueMakowski I'm happy to have a crack at this. I'm just curious if we previously have handed error terms in `parameters` in a particular way for aov?
