### ISSUE TITLE
Support Wilcoxon/Mann-Whitney tests (stats::wilcox.test in R)

### ISSUE THREAD

**Issue by whryan** [easystats/report#169]
**Describe the solution you'd like**
Support reporting for wilcox.test. E.g. wilxoc.test(x, y) %>% report() should return a report. 

**How could we do it?**
Similar to how other tests are reported, presumably.

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil could you look into this?

**Comment by IndrajeetPatil** [comment]
``` r
library(report)

x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

wilcox.test(x, y, paired = TRUE) |> report()
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Wilcoxon signed rank exact test testing the difference in ranks between x and y suggests that the effect is positive, statistically significant, and very large (W = 40.00, p = 0.039; r (rank biserial) = 0.78, 95% CI [0.30, 0.94])
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/easystats/report/commit/1d15441e0d7442a0837d2c75d6931096c33349ca

The exact text might change a little by the time this makes to CRAN, but this is just to show that `report` works with this test now.

**Comment by whryan** [comment]
Looks amazing!
