### ISSUE TITLE
Minor addition

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#174]
- [ ] Currently, we say e.g., `Effect sizes were labelled using Funder's (2019) recommendations.` We can add ` (interpret with caution)` just to highlight the limitations of automated labelling.

**Comment by DominiqueMakowski** [comment]
actually no, people should KNOW that they should interpret everything with caution, but it's weird to just add that here and repeat it over and over

**Comment by mattansb** [comment]
That should really be in the startup message of the package...
