### ISSUE TITLE
Error: package or namespace load failed for ‘report’: object ‘skewness’ is not exported by 'namespace:parameters'

### ISSUE THREAD

**Issue by hchats** [easystats/report#192]
I get an error when I try to install and load library "report". 

When I run:
install.packages("report")
library(report)

I get the following output:
Error: package or namespace load failed for ‘report’: object ‘skewness’ is not exported by 'namespace:parameters'

I am using RStudio Version 1.4.1106.

However, I am a beginner so I realize that there is probably a very easy solve to this. Is it likely because I have another package installed with some skewness function?

**Comment by IndrajeetPatil** [comment]
It is possible that you are working with the development versions of one of the packages.

Try updating all packages to their development versions and then see if the problem persists:

```r
easystats::install_latest()
```

**Comment by hchats** [comment]
Thanks for your quick reply @IndrajeetPatil. I just did that and received the following:

Error in loadNamespace(x) : there is no package called ‘easystats’

I then tried to re-install and received the following:

Error: Failed to install 'report' from GitHub: HTTP error 403. API rate limit exceeded for 185.56.103.172. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) Rate limit remaining: 0/60 Rate limit reset at: 2021-07-06 20:30:13 UTC To increase your GitHub API rate limit - Use `usethis::browse_github_pat()` to create a Personal Access Token. - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

I am using R Version 4.1.0 too.

**Comment by IndrajeetPatil** [comment]
Ah, okay.

Refresh your R session and try:

```r
install.packages('easystats', repos = 'https://easystats.r-universe.dev')
```

**Comment by hchats** [comment]
Fixed! Thank you so much!

**Comment by IndrajeetPatil** [comment]
Great!
