### ISSUE TITLE
Error: package or namespace load failed for ‘report’:

### ISSUE THREAD

**Issue by petedatasci** [easystats/report#193]
Once I've installed and run library(report) I get the following warning: 

```r
"Error: package or namespace load failed for ‘report’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘parameters’ 0.14.0 is being loaded, but >= 0.14.0.1 is required".
```

So I install the development version of parameters `remotes::install_github("easystats/parameters")` but then get the following warning message:

```r
"Error: package or namespace load failed for ‘report’:
object ‘skewness’ is not exported by 'namespace:parameters'".
```
Am I missing something obvious or doing something wrong?

Thanks

**Comment by IndrajeetPatil** [comment]
Hi.

Can you please run the following, refresh your R session, and see if it works?

```r
install.packages('easystats', repos = 'https://easystats.r-universe.dev')
```

**Comment by petedatasci** [comment]
Hi,

Tried that this morning and I'm still seeing the same error message when I run library(report). If I run library(easystats) I also get:

 Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: package or namespace load failed for ‘report’:
 object ‘skewness’ is not exported by 'namespace:parameters'

**Comment by IndrajeetPatil** [comment]
Strange. Here is a reproducible example showing that the solution suggested above works:

``` r
install.packages('easystats', repos = 'https://easystats.r-universe.dev')
#> Installing package into '/Users/patil/Library/R/x86_64/4.1/library'
#> (as 'lib' is unspecified)
#> 
#> The downloaded binary packages are in
#>  /var/folders/_p/55p16nb13cs7yy707d8l_v1s_rmpr4/T//RtmpU20sks/downloaded_packages
library(easystats)
#> # Attaching packages: easystats 0.4.2
#> ✔ insight     0.14.2.1     ✔ datawizard  0.1.0.9000
#> ✔ bayestestR  0.10.5       ✔ performance 0.7.2.1   
#> ✔ parameters  0.14.0.1     ✔ effectsize  0.4.5.1   
#> ✔ modelbased  0.8.0        ✔ correlation 0.7.0     
#> ✔ see         0.6.5        ✔ report      0.3.5
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by petedatasci** [comment]
Could it be something to do with OneDrive perhaps? Not had this issue before, but you never know:

install.packages('easystats', repos = 'https://easystats.r-universe.dev')
#> Installing package into 'C:/Users/peter/OneDrive - Edinburgh Napier University/Documents/R/win-library/4.1'
#> (as 'lib' is unspecified)
#> package 'easystats' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\peter\AppData\Local\Temp\RtmpI9KvaT\downloaded_packages
Created on 2021-07-18 by the reprex package (v2.0.0)

library(easystats)
#> Error: package or namespace load failed for 'easystats':
#>  .onAttach failed in attachNamespace() for 'easystats', details:
#>   call: NULL
#>   error: package or namespace load failed for 'report':
#>  object 'skewness' is not exported by 'namespace:parameters'

**Comment by bwiernik** [comment]
You should not install R packages into OneDrive or any other cloud folder. This is likely to produce a variety of errors and corruption.

**Comment by petedatasci** [comment]
After making my R package library local on my machine, it looks like the issue has resolved itself.
