### ISSUE TITLE
Binary Sex/Gender

### ISSUE THREAD

**Issue by drfeinberg** [easystats/report#200]
**Describe the bug**
Reporting sex only says 1 sex. e.g. 50% we're female. But sex and gender are not binary so you need to report what the other 50% were.

**To Reproduce**
Steps to reproduce the behaviour:
data <- data.frame(
  "Age" = c(22, 23, 54, 21),
  "Sex" = c("F", "F", "M", "M")
)

paste(
  report_participants(data, spell_n = TRUE),
  "were recruited in the study by means of torture and coercion."
)

**Expected behaviour**
50% Male 50% Female

**Screenshots**

**Specifiations (please complete the following information):**
 - Package Version [e.g. 0.2.1]

**Comment by drfeinberg** [comment]
Brenton you do so much. Thanks for all you do.

**Comment by DominiqueMakowski** [comment]
@bwiernik could you eventually help improve the function I'm not sure how to best make it flexible to accommodate all use-cases and best practices. It's probably this chunk that needs to be improved:

https://github.com/easystats/report/blob/fb509f8b7ea2c2b959173f38dc838c0eea855589/R/report_participants.R#L195-L202

**Comment by bwiernik** [comment]
Yeah, I'll port some stuff from gendercodeR to make that a bit more robust

**Comment by drfeinberg** [comment]
Sorry... I was cleaning up and thought this was done.  Can I help in any way?

**Comment by bwiernik** [comment]
Haven’t had time to work on this yet. A PR to change the report to counts for each group would be great

**Comment by drfeinberg** [comment]
Okay, so I've started working on this and found that the variable is sex, not gender.  However, the code greps for gender when looking for the variable sex, treating them as one construct.

Just curious how you want me to proceed. From an inclusivity standpoint, my preference is treat gender and sex separately here.  I can separate the code into difference searches for different variables provided by the user. I see how the code works.

**Comment by bwiernik** [comment]
Can you post your code to gist.GitHub.com and I can incorporate it?

**Comment by drfeinberg** [comment]
Here you go.  Like I said, I haven't been able to test it, so sorry if it's buggy.
https://gist.github.com/drfeinberg/0968ba7a5581cd69684b63e77ba5ab30

**Comment by drfeinberg** [comment]
So,  I got it going on my machine.  I'll try to fix the bugs and I can try to do a proper PR when that's done
