### ISSUE TITLE
Plz sir give me fb report git clone

### ISSUE THREAD

**Issue by Deepakchauhan15** [easystats/report#201]
**Describe the bug**
A description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Specifiations (please complete the following information):**
 - Package Version [e.g. 0.2.1]

**Comment by bwiernik** [comment]
I am not sure what you are saying. Can you please open a new issue with a clear description of the problem you are having?
