### ISSUE TITLE
`report()` for htest/cor.test errors

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#203]
``` r
report::report(cor.test(mtcars$wt, mtcars$mpg))
#> Warning: This 'htest' method is not (yet?) supported.
#> Returning 'parameters::model_parameters(model)'.
#> Error in abs(r): non-numeric argument to mathematical function
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Used to work in the vignette:
https://easystats.github.io/report/articles/report.html

**Comment by mattansb** [comment]
Yes, I've made a chance in `effectsize` making it easier to maintain. Since eg `cor.test()` and `fisher.test()` already return effect sizes (r, OR) `effectsize()` was just reorganizing the output... But `parameters` already does that! So it just passes them to `parameters()` instead.

The only `htest` tests that actually need something computed by `effectaize()`
- t.test
- chisq.test
- oneway.test
- mcnemar.test
- wilcoxon.test
- kruskal.test
- friedman test 

All others are passed to `parameters()`

**Comment by strengejacke** [comment]
So what does this mean for _report_?

**Comment by mattansb** [comment]
That it (and I guess also `parametet`) shouldn't use `effectsize()` in those cases where it gives the parameters table?
Report shouldn't be using effectsize directly at all, no? It should be using parameters.

**Comment by strengejacke** [comment]
Ok, I think this should be fixed by @DominiqueMakowski who is more familiar with the code base :-)

**Comment by DominiqueMakowski** [comment]
> Report shouldn't be using effectsize directly at all, no? It should be using parameters.

Huh yeah that was the goal but at the time there was more information and flexibility in using directly effectisze. But dropping the reliance on effectsize will require some substantial change because now in report the general logic is 1) get the effect size table 2) get the parameters table 3) get the performance table 4) assemble; so we'd need to merge step 1 and 2 and have the report_effectsize that subsets the general table

**Comment by DominiqueMakowski** [comment]
Also we need to make sure that all the attributes that were in effecsize() are carried on the parameters() (rule's used etc)

**Comment by bwiernik** [comment]
I'd be okay with keeping the interpretation rules in *effectsize*. *effectsize* is upstream of *report*, so I don't see the issue with keeping they dependency

**Comment by DominiqueMakowski** [comment]
But I think the problem that we have now is that essentially first we run effectsize, and then we run parameters, which itself re-run effectsize anyway. So it's not super efficient, and this contributes to make report quite slow (even though efficiency is not yet one of our main goal but still). So we might as well get everything directly from parameters (the valeus of the effectsize) then the interpretation is done in the textual transformation of the values in report_effectsize using effectsize if I remember

**Comment by bwiernik** [comment]
I think the problem is that parameters and effectsize should not depend on each other.  That's a problem (and the source of a bunch of our circular issues). One needs to be higher precedence

**Comment by DominiqueMakowski** [comment]
this was originally how I saw things, that the 3 components (performance indices, parameters stats and effectsizes) would be joined at a higher level (report), but now it's too late for that, and having the effectsizes of parameters in parameters is an important feature (especially since getting the full tables from report is not as stable or robust)

**Comment by bwiernik** [comment]
We can't have circular dependencies. Either effectsize or parameters needs to be the higher one

**Comment by DominiqueMakowski** [comment]
parameters is the higher one and calls effectsize, but currently in report we still rely on both, and the goal is to rely only on parameters (which itself relies on effectsize)

**Comment by bwiernik** [comment]
Here when I say "higher", I meant fewer dependencies. 

The problem ultimately seems to be that parameters and effectsize call each other. That shouldn't be. One needs to be exclusively higher

**Comment by mattansb** [comment]
I think once report is stable enough, we should move the parameter + effectsize table merging from parameters to report.

In the meantime, I suggest @strengejacke that any call to effectsize from parameters should be wrapped in a tryCatch and tested conditional on the latest version of effectsize.

**Comment by IndrajeetPatil** [comment]
We can't submit to CRAN before fixing this issue. So this has become a high priority now. We have only one week left.

**Comment by IndrajeetPatil** [comment]
``` r
library(report)

report(cor.test(iris$Sepal.Width, iris$Sepal.Length))
#> Error in abs(r): non-numeric argument to mathematical function
```

<sup>Created on 2022-01-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by DominiqueMakowski** [comment]
fixed for t-test and cor.test but needs double check for whether wilcoxon tests is correct @mattansb @strengejacke @IndrajeetPatil

**Comment by DominiqueMakowski** [comment]
And yes effect sizes should probably be pulled directly from parameters instead of doing it directly with effectsize, which should simplify the code quite a lot... feel free for the parameters expert to help ^^

**Comment by mattansb** [comment]
@DominiqueMakowski can you point me to where Wilcoxon is used?

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/report/blob/3ae96a21e0e36f70f8b1d470aeb4ae57efe8bbfe/R/report.htest.R#L72-L98

**Comment by IndrajeetPatil** [comment]
It's definitely broken:

``` r
library(report)

x <- c(1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
set.seed(123)
report(wilcox.test(x, y, paired = TRUE, data = mtcars))
#> Error in `[.data.frame`(table, c(estimate, paste0(estimate, c("_CI_low", : undefined columns selected
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by mattansb** [comment]
Yeah, I have no idea how to fix this - I'm don't even know what the function is suppose to return?
What I do see is that the parameter table does not include the *r<sub>rbs</sub>* at all, so this would either be requested from `parameters(rank_biserial = TRUE)` or directly from `effectsize()` (neither is happening currently).

**Comment by IndrajeetPatil** [comment]
This is what if used to return:

```r
library(report)

x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

wilcox.test(x, y, paired = TRUE) |> report()
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Wilcoxon signed rank exact test testing the difference in ranks between x and y suggests that the effect is positive, statistically significant, and very large (W = 40.00, p = 0.039; r (rank biserial) = 0.78, 95% CI [0.30, 0.94])
```

I need to be on duty now but will have a look later if I can retrace where the problem is occurring.

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/report/blob/3ae96a21e0e36f70f8b1d470aeb4ae57efe8bbfe/R/report.htest.R#L75-L77


so in the wilcox case we need to replace the current thing and call `table <- parameters(rank_biserial = TRUE)` and then get the stuff

**Comment by DominiqueMakowski** [comment]
And this only applies for correlations then:

https://github.com/easystats/report/blob/3ae96a21e0e36f70f8b1d470aeb4ae57efe8bbfe/R/report.htest.R#L66-L70

**Comment by DominiqueMakowski** [comment]
> this would either be requested from parameters(rank_biserial = TRUE) or directly from effectsize()

Getting effectsizes fails @mattansb, not sure what's the right way to get them?

``` r
library(report)

x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

x <- wilcox.test(x, y, paired = TRUE)

parameters::parameters(x, rank_biserial = TRUE)
#> Error: Unable to retrieve data from htest object.
#> Try using'cles()' directly.
effectsize::effectsize(x)
#> Error: Unable to retrieve data from htest object.
#> Try using'cles()' directly.


x <- c(1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
set.seed(123)
x <- wilcox.test(x, y, paired = TRUE, data = mtcars)

parameters::parameters(x, rank_biserial = TRUE)
#> Error: Unable to retrieve data from htest object.
#> Try using'cles()' directly.
effectsize::effectsize(x)
#> Error: Unable to retrieve data from htest object.
#> Try using'cles()' directly.
```

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I'd say skip it for now, maybe a warning for wilcox, and add later?

**Comment by mattansb** [comment]
If you name the result of `wilcox.test()` `x` then you cannot recover the data - this is not an `effectsize` issue:

``` r
x <- c(1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

W <- wilcox.test(x, y, paired = TRUE, data = mtcars)
effectsize::effectsize(W)
#> r (rank biserial) |       95% CI
#> --------------------------------
#> 0.78              | [0.30, 0.94]


x <- wilcox.test(x, y, paired = TRUE, data = mtcars)
insight::get_data(W)
#> NULL
```

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Not sure why `parameters` fails...

**Comment by strengejacke** [comment]
> Not sure why `parameters` fails...

This is the code in _parameters_ that fails.

``` r
x <- c(1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)

W <- wilcox.test(x, y, paired = TRUE, data = mtcars)
effectsize::effectsize(W, type = "r_rank_biserial", ci = .9, verbose = TRUE)
#> Error in do.call(f, c(args, dots)): 'what' must be a function or character string
```

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
Did that ever work?
`r_rank_biserial` is not a valid type, should be `rank_biserial`.

**Comment by DominiqueMakowski** [comment]
![](https://cdn.vox-cdn.com/thumbor/rxKe5Ak6St_w_qKd0a_eGFPrEdY=/0x0:800x450/1400x933/filters:focal(325x11:453x139):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/58204065/spiderman_double.0.jpg)

**Comment by mattansb** [comment]
I've made a make-shift patch in effectsize - will submit to cran today.

**Comment by DominiqueMakowski** [comment]
so we wait for that to go in before submitting report

**Comment by mattansb** [comment]
Patched effectsize is on CRAN, but I think report still needs to be fixed.

**Comment by DominiqueMakowski** [comment]
However there's a slight inconsistency the estiamte is named "r_rank_biserial" and then CIs "rank_biserial_CI_low" (i.e., without the `r_`

**Comment by mattansb** [comment]
That is prob coming from `parameters`, in `effectsize`:

``` r
(rb <- effectsize::rank_biserial(mpg ~ am, data = mtcars))
#> r (rank biserial) |         95% CI
#> ----------------------------------
#> -0.66             | [-0.84, -0.36]

colnames(rb)[1]
#> [1] "r_rank_biserial"
```

<sup>Created on 2022-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
