### ISSUE TITLE
Should this commented code be removed?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#218]
@DominiqueMakowski 

https://github.com/easystats/report/blob/05bc6dae4b9086e1773d4516d8ec396ce13476f5/R/report_info.R#L115-L217

Or be moved to the `WIP` folder?

**Comment by DominiqueMakowski** [comment]
I think it is some old code that got re-written above

**Comment by bwiernik** [comment]
![image](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi.myniceprofile.com%2F1134%2F113455.gif&f=1&nofb=1)
