### ISSUE TITLE
`{report}` is archived?!

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#230]
@DominiqueMakowski Did you receive any email?!

https://cran.r-project.org/web/packages/report/index.html

![image](https://user-images.githubusercontent.com/11330453/154795801-620648a1-28bc-47f9-91bd-5a08ea3c0618.png)

**Comment by strengejacke** [comment]
😱 

There was an issue (https://github.com/easystats/report/issues/226), but you already fixed it. I thought that the update was already submitted... @DominiqueMakowski ?

**Comment by strengejacke** [comment]
Here: https://github.com/easystats/report/issues/214

On its way to cran...

**Comment by IndrajeetPatil** [comment]
But #226 is from Feb, while #214 is from Jan.

I fixed #226, but I am not the maintainer for this package, so I wasn't sure if this was something that CRAN wanted fixed, or it's just something that you (Daniel) noticed on CRAN checks and created an issue.

@DominiqueMakowski Did you actually receive any email about this? Maybe it went to spam?

**Comment by strengejacke** [comment]
True, #226 must have been new issues.

**Comment by DominiqueMakowski** [comment]
What?? No didn't receive anything, I'll submit

**Comment by bwiernik** [comment]
Bizarre

**Comment by DominiqueMakowski** [comment]
I doubled check and no, didn't receive any email since the 17th Jan one 🤔

**Comment by DominiqueMakowski** [comment]
On the 2nd feb:

```
Dear package maintainer,

this notification has been generated automatically.
Your package report_0.5.0.tar.gz has been built for Windows and
will be published within 24 hours in the corresponding CRAN directory.
```

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/e5F5Oc56rTjb/00check.log

I have these errors in local checks too but somehow cannot find the origin

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski You can pull changes from `master` branch, and try again. It should work now.

**Comment by IndrajeetPatil** [comment]
It's back on CRAN!
https://cran.r-project.org/web/packages/report/index.html

We should write to Uwe and Kurt, and let them know that this happened. Maybe there is a bug in CRAN system that sometimes archives without informing the maintainers first. 

If you agree, I can write an email and cc you.

**Comment by DominiqueMakowski** [comment]
good idea!

**Comment by strengejacke** [comment]
@DominiqueMakowski did you submit an update or was it unarchived?

**Comment by DominiqueMakowski** [comment]
I submitted an update yesterday

**Comment by IndrajeetPatil** [comment]
The takeaway lesson from this is that we should be checking CRAN status regularly (at least biweekly), and if we see any errors, we should fix them and submit a new version to CRAN _irrespective_ of whether they email us or not.

``` r
easystats::CRAN_checks()
#> insight     2 Notes
#> datawizard  Ok
#> bayestestR  9 Notes
#> performance 1 Note
#> parameters  1 Note
#> effectsize  Ok
#> modelbased  10 Errors
#> correlation Ok
#> see         Ok
#> report      Ok
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by strengejacke** [comment]
We have this short cut, that could be used when loading _easystats_:

``` r
easystats:::.cran_checks(FALSE)
#> Warnings or errors in CRAN checks for package(s) 'modelbased'.

easystats:::.cran_checks(TRUE)
#> insight     2 Notes
#> datawizard  Ok
#> bayestestR  9 Notes
#> performance 1 Note
#> parameters  1 Note
#> effectsize  Ok
#> modelbased  10 Errors
#> correlation Ok
#> see         Ok
#> report      Ok
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, if we consider bringing this meta-package to CRAN, I'm not sure this is a useful information for users.

**Comment by mattansb** [comment]
We can build a GH-action to run this function once a week (:

**Comment by bwiernik** [comment]
I agree that if the meta package is user facing, we don't want the cran_checks() function to be run on load or be exported.
