### ISSUE TITLE
Printing truncated

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#237]
This is what gets printed in the console:

``` r
report::report(cor.test(iris$Sepal.Length, iris$Sepal.Width))
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Pearson's product-moment correlation between iris$Sepal.Length and iris$Sepal.Width is negative, statistically not significant, and small (r = -0.12, 95% CI [-0.27, 0.04], t(148) = -1.44, p = 0.152)
```

<sup>Created on 2022-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

but this is what shows in the [knitted version](https://easystats.github.io/modelbased/articles/derivatives.html): 

![image](https://user-images.githubusercontent.com/8875533/159145629-2a51ac41-971f-4681-bbd9-802486ae9408.png)

the first sentence disappeared 🤔

**Comment by IndrajeetPatil** [comment]
If I knit the `derivatives.Rmd` locally, I can't reproduce this. Are you sure you are working with GitHub versions of packages (esp. _effectsize_)?

![image](https://user-images.githubusercontent.com/11330453/159150376-bc42091e-a319-468d-9f67-c4b1e11341d9.png)
