### ISSUE TITLE
Warning: Unable to retrieve data from htest object. Using t_to_d() approximation.

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#245]
**Question and context**

I noticed I was getting different Cohen's _d_ values using the `report` function on a `t.test` model object, than when getting the value directly from other packages. The reason is clearly stated in a warning that describes a `t_to_d()` approximation in the absence of the original data.

``` r
# report
model <- t.test(len ~ supp, data = ToothGrowth, paired = FALSE)
as.data.frame(report::report(model)) -> table1
#> Warning in .effectsize_t.test(model, type = type, verbose = verbose, ...):
#> Unable to retrieve data from htest object. Using t_to_d() approximation.
d1 <- table1$d
# Warning message: In .effectsize_t.test(model, type = type, verbose = verbose, ...) : Unable to retrieve data from htest object. Using t_to_d() approximation.

# effectsize
effectsize::cohens_d(len ~ supp, data = ToothGrowth, paired = FALSE, ci = TRUE) -> table2
d2 <- table2$Cohens_d

# effsize
effsize::cohen.d(len ~ supp, data = ToothGrowth) -> table3
d3 <- table3$estimate

# rstatix
rstatix::cohens_d(len ~ supp, data = ToothGrowth, paired = FALSE, ci = TRUE) -> table4
d4 <- table4$effsize

pkg.names <- c("report", "effectsize", "effsize", "rstatix")
d <- c(d1, d2, d3, d4)
OP.table <- data.frame(pkg.names, d)
OP.table
#>    pkg.names         d
#> 1     report 0.5150626
#> 2 effectsize 0.4945201
#> 3    effsize 0.4945201
#> 4    rstatix 0.4945201
```

<sup>Created on 2022-05-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The value difference isn't huge, but it feels right to report the precisely correct value rather than an estimation, if possible. So I was simply wondering if there was any way to provide it with the original data to get the correct _d_ value since obviously it cannot get it from the `htest` object. I've tried:

`report::report(model, data = ToothGrowth)`

And looked at the arguments but cannot find a way to do this. If we have no way to avoid resorting to a second function to get the correct _d_ value, does it not slightly defeat the spirit of the report/easystats-verse?

**Comment by strengejacke** [comment]
Some - not all - htest objects allow to recover the data from the environment or the returned htest-object directly. In your example, there's almost no way to do that:

``` r
t.test(len ~ supp, data = ToothGrowth, paired = FALSE) |> str()
#> List of 10
#>  $ statistic  : Named num 1.92
#>   ..- attr(*, "names")= chr "t"
#>  $ parameter  : Named num 55.3
#>   ..- attr(*, "names")= chr "df"
#>  $ p.value    : num 0.0606
#>  $ conf.int   : num [1:2] -0.171 7.571
#>   ..- attr(*, "conf.level")= num 0.95
#>  $ estimate   : Named num [1:2] 20.7 17
#>   ..- attr(*, "names")= chr [1:2] "mean in group OJ" "mean in group VC"
#>  $ null.value : Named num 0
#>   ..- attr(*, "names")= chr "difference in means between group OJ and group VC"
#>  $ stderr     : num 1.93
#>  $ alternative: chr "two.sided"
#>  $ method     : chr "Welch Two Sample t-test"
#>  $ data.name  : chr "len by supp"
#>  - attr(*, "class")= chr "htest"
```

But yes, one solution would be to add an optional `data` argument for these edge cases.

**Comment by bwiernik** [comment]
I like the idea of a data argument

**Comment by rempsyc** [comment]
``` r
packageVersion("effectsize")
#> [1] '0.8.8'
packageVersion("report")
#> [1] '0.5.8'

# report
x <- t.test(len ~ supp, data = ToothGrowth)
x <- report::report(x, data = ToothGrowth)
x <- as.data.frame(x)$Cohens_d
x
#> [1] 0.4945201
  
# effectsize
y <- effectsize::cohens_d(len ~ supp, data = ToothGrowth)[,"Cohens_d"]
y
#> [1] 0.4945201

# comparison
x == y
#> [1] TRUE
```

<sup>Created on 2024-05-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
![FridayHappyDanceGIF](https://github.com/easystats/report/assets/35330040/844217db-c612-4b10-b417-997ac32d8968)
