### ISSUE TITLE
namespace ‘datawizard’ 0.4.0 is already loaded, but >= 0.4.0.3 is required

### ISSUE THREAD

**Issue by stevevaius77** [easystats/report#249]
I have an issue with library after installing it. My system is RStudio 2022.02.2 Build 485 and R 4.2.0. After installing it, report for iris 
`report("iris")` 
dataset working properly but running any models ( `report(t.test(mtcars$mpg ~ mtcars$am))` ) give error as 
    ```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
    namespace ‘datawizard’ 0.4.0 is already loaded, but >= 0.4.0.3 is required
```

**Comment by IndrajeetPatil** [comment]
You just need to install the development version of _datawizard_ package. So run the following:

```r
remotes::install_github("easystats/datawizard")
```

If there are other _easystats_ packages whose development versions (non-CRAN versions, i.e.) are required, you will need to repeat the same process for those packages.

**Comment by strengejacke** [comment]
The most simple thing is to install _easystats_, and then use `install_latest()`:

```r
install.packages("easystats", repos = "https://easystats.r-universe.dev")
easystats::install_latest()
```
