### ISSUE TITLE
Fixing build failures

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#252]
Builds seem to be failing with the following error:

```r
Quitting from lines 105-108 (report.Rmd) 
Error: Error: processing vignette 'report.Rmd' failed with diagnostics:
argument is of length zero
--- failed re-building ‘report.Rmd’
SUMMARY: processing the following file failed:
  ‘report.Rmd’
Error: Error: Vignette re-building failed.
Execution halted
```

But if I locally knit this vignette, I see no error.

Does this have to do with updates to any of the dependencies? I bumped all _easystats_ dependency versions, but the issue is still there.

**Comment by strengejacke** [comment]
One issue is fixed, but `.find_regression_estimate()` still fails, because the coefficients are named "Std. Coefficient", but the stored name-attribute contains "Coefficient".

**Comment by strengejacke** [comment]
Is this still an issue?

**Comment by IndrajeetPatil** [comment]
I don't think so.
