### ISSUE TITLE
Support chi-sq test reporting

### ISSUE THREAD

**Issue by jmattnavarro** [easystats/report#258]
Adding functionality for reporting the results of a chi-square test output (and other nonparametric tests).

Thank you for all of your work!!

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil could you look into this? I don't work with Chi² but it should be pretty straightforward to add based on the t-test template

**Comment by mattansb** [comment]
Something like this for the text:

## For `Pearson's Chi-squared test`:
```R
htest <- chisq.test(mtcars$cyl, mtcars$am)

V <- effectsize::cramers_v(htest)

glue::glue(
  "The Chi-squared test of independance between {data_name} ",
  "suggests a {size}, {sig} association ",
  "Chi^2({df})={chisq}, {p}, ",
  "Cramer's V = {v}, {level} CI (one-sided) [{low}, {high}].",

  data_name = htest$data.name,
  size = effectsize::interpret_phi(V[[1]]),
  sig = effectsize::interpret_p(htest$p.value),
  df = htest$parameter,
  chisq = insight::format_value(htest$statistic),
  p = insight::format_p(htest$p.value),
  v = insight::format_value(V[[1]]),
  level = insight::format_percent(V$CI, digits = 0),
  low = insight::format_value(V$CI_low),
  high = insight::format_value(V$CI_high)
)
```

> The Chi-squared test of independance between mtcars$cyl and mtcars$am suggests a very large, significant association Chi^2(2)=8.74, p = 0.013, Cramer's V = 0.52, 95% CI (one-sided) [0.18, 1.00].

## For `Chi-squared test for given probabilities`
```R
htest <- chisq.test(table(mtcars$cyl), p = c(0.1, 0.3, 0.6))

normchi <- effectsize::normalized_chi(htest)
  
glue::glue(
  "The Chi-squared test for goodness-of-fit of {data_name} to {dist} ",
  "suggests a {size}, {sig} deviation from the expected distribution ",
  "Chi^2({df})={chisq}, {p}, ",
  "Norm. Chi = {v}, {level} CI (one-sided) [{low}, {high}].",

  data_name = htest$data.name,
  dist = ifelse(!grepl("non", attr(normchi, "table_footer")),
                "a uniform distribution",
                paste0("a distribution of [",paste0(names(htest$expected), ": n=", htest$expected, collapse = ", "),"]")),
  size = effectsize::interpret_phi(normchi[[1]]),
  sig = effectsize::interpret_p(htest$p.value),
  df = htest$parameter,
  chisq = insight::format_value(htest$statistic),
  p = insight::format_p(htest$p.value),
  v = insight::format_value(normchi[[1]]),
  level = insight::format_percent(normchi$CI, digits = 0),
  low = insight::format_value(normchi$CI_low),
  high = insight::format_value(normchi$CI_high)
)
```
> The Chi-squared test for goodness-of-fit of table(mtcars$cyl) to a distribution of [4: n=3.2, 6: n=9.6, 8: n=19.2] suggests a medium, significant deviation from the expected distribution Chi^2(2)=21.12, p < .001, Norm. Chi = 0.27, 95% CI (one-sided) [0.17, 1.00].

**Comment by IndrajeetPatil** [comment]
I am afraid to step in the `{report}` codebase given its implementation complexity 😭

**Comment by mattansb** [comment]
Aren't we all......

**Comment by strengejacke** [comment]
I'm doing a bit refactoring in #287, so hopefully it will become easier (given that PR will be successful)

**Comment by strengejacke** [comment]
ok, the template is here:
https://github.com/easystats/report/pull/287/commits/0619d120a4a21ac6be3de7b69a700b4900d2cbb6

But I don't know how to implement (what should be reported etc.). I leave it to you to continue working on that PR... :-)

**Comment by strengejacke** [comment]
You may look at the other templates for t-test (https://github.com/easystats/report/blob/fb1a304456e28f003bd55c1fa0a59775a5016148/R/report_htest_ttest.R) or wilcox... The idea is just to have an own file for each htest type, for easier maintanance.
