### ISSUE TITLE
report(lmer-model) is slow for large data. 

### ISSUE THREAD

**Issue by huelemeier** [easystats/report#270]
**Question and context**
I have a dataset with ~9000 rows and 23 columns. To test my research question, I use a linear mixed model (lmer). Reporting the anova of my lmer-model works fine. However, reporting the model using report(lmer-model) takes much time, more than 10 minutes. Stopping R leads to crashes.
Tests using lm, t-tests, or effect sizes went smoothly. Simpler lmer-models with solely one predictor also cause these troubles. When I decrease the size of the dataset significantly, the report works smoothly.
Is there something I can do to minimize these troubles?
Thanks in advance!

**Comment by strengejacke** [comment]
We should profile the function, I guess it's due to calculating R2 or ICC. @huelemeier could you try `performance::r2()` on your model and say if this is slow or not?

**Comment by strengejacke** [comment]
Ups, closes while writing - was this intentional?

**Comment by huelemeier** [comment]
I applied performance::r2() on my model and it worked perfectly.

I closed that thread because I read about a similar problem (thread from 7th July).

**Comment by IndrajeetPatil** [comment]
Closed in favour of #264
