### ISSUE TITLE
report_participants struggles with missing values in factors

### ISSUE THREAD

**Issue by LukasWallrich** [easystats/report#303]
I realised that this issue description was not quite right - the problem is that NAs in factors cause warnings and are not included in the summary, while NAs in corresponding character variables are treated correctly. In my view, the following two should give the same result:

``` r
x <- data.frame(race = factor(c(LETTERS[1:4], NA)))
report::report_participants(x)
#> Warning in `[<-.factor`(`*tmp*`, iseq, value = "missing"): invalid factor level,
#> NA generated
#> [1] "5 participants (Race: 20.00% A, 20.00% B, 20.00% C, 20.00% D)"

x <- data.frame(race = c(LETTERS[1:4], NA))
report::report_participants(x)
#> [1] "5 participants (Race: 20.00% A, 20.00% B, 20.00% C, 20.00% D, 20.00% missing)"
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
Thanks for pointing this out! I will have a look shortly and attempt to fix it.
