### ISSUE TITLE
Fix remaining failing tests (unmatching snapshot tests depending on OS)

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#312]
Edit: ivreg test no longer seems a problem, so I will redirect this issue to another failing test (next comment).

<details>
<summary>Outdated</summary>

Running tests on Windows fails for `ivreg`: `Following elements are no valid metric: 'Sargan' and 'Wu_Hausman'`

Full message:

```
Failure (test-report.ivreg.R:13): report-survreg
Snapshot of code has changed (variant 'windows'):
old[1:10] vs new[1:15]
  "Code"
  "  report(ivr)"
  "Message <simpleMessage>"
- "  Formula contains log- or sqrt-terms. See help(\"standardize\") for how"
- "    such terms are standardized."
- "  Formula contains log- or sqrt-terms. See help(\"standardize\") for how"
- "    such terms are standardized."
+ "  Formula contains log- or sqrt-terms."
+ "    See help(\"standardize\") for how such terms are standardized."
+ "Warning <simpleWarning>"
+ "  Following elements are no valid metric: `Sargan` and `Wu_Hausman`"
+ "Message <simpleMessage>"
+ "  Formula contains log- or sqrt-terms."
+ "    See help(\"standardize\") for how such terms are standardized."
and 5 more ...
```

Not sure if those new tests results are expected (and could therefore be accepted) or whether it is an indication of a bug elsewhere.

<br>
</details>

**Comment by rempsyc** [comment]
It seems the remaining tests that are failing relate to non-matching snapshots tests on the following OS:

- [ ] windows-latest (oldrel)
- [ ] windows-latest (4.1)
- [ ] ubuntu-latest (oldrel)

I'm not quite sure as to how to address this since the recommended options to review or accept the snapshot changes are normally done interactively, but when testing locally, you can only test on one OS. So how to review/accept changes for these other OS?

**Comment by IndrajeetPatil** [comment]
Yeah, unfortunately, this is a real pain in the ass. 

The easiest option for us is to decide on one OS and generate snapshot only for that OS and skip tests for all other OS. 

But how do we decide which one? Mac or Windows?

**Comment by strengejacke** [comment]
Windows. We can ignore Mac.

**Comment by IndrajeetPatil** [comment]
![InsignificantInfiniteArrowcrab-size_restricted](https://user-images.githubusercontent.com/11330453/208842389-034de6b0-f8e9-46c0-8bd3-5b9214e52d14.gif)

**Comment by rempsyc** [comment]
Perhaps I'm missing something, but as to the current problem, it is failing only on some Windows machines, not all. So even if we do change it to Windows, it might not solve our problems? I don't know if we can additionally specify the windows/R version or whatever these different Windows OS represent in the snapshots or if that's a GHA issue.

**Comment by rempsyc** [comment]
Closing this since we are now testing on Windows only.
