### ISSUE TITLE
Fix `Rd files with duplicated alias 'report'` R CMD check warning

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#313]
It seems that currently the only reason R CMD check is failing on the main branch for most OS is because of the following warning:

```
checking Rd metadata ... WARNING
  Rd files with duplicated alias 'report':
    'report-package.Rd' 'report.Rd'
```

@etiennebacher Is this from when we added a package description file for each package? Any idea how to fix that?

**Comment by etiennebacher** [comment]
Ah right there already was an Rd file with this alias. I'll fix it
