### ISSUE TITLE
Fix use of base R pipes in vignette

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#315]
It seems that some vignettes (`report_table.Rmd`) use the native R pipe, which seems to fail tests on older R versions tested. I suppose the fix here is to remove the pipe? Or was there a mention at some point that there should be a conversion happening automatically from the native pipe for older versions?

```r
Error: Error: processing vignette 'report_table.Rmd' failed with diagnostics:
<text>:9:4: unexpected '>'
8:   report_table(results3)
9: ) |>
      ^
--- failed re-building 'report_table.Rmd'
SUMMARY: processing the following file failed:
  'report_table.Rmd'
```

Currently affected versions are:
- [x] windows-latest (3.6)
- [x] ubuntu-latest (oldrel-2)
- [x] ubuntu-latest (oldrel-3)

@etiennebacher do you know anything about that native pipe conversion thing?

**Comment by strengejacke** [comment]
> do you know anything about that native pipe conversion thing?

When you compile source code / build binaries on an R version that supports the pipe, it's internally converted into R code that can be run on older R systems. However, it requires a new R version to do this. We could simply skip vignettes on older R versions. You can't copy/paste them on older R versions then, though.

**Comment by IndrajeetPatil** [comment]
I would say, just don't use native pipes in vignettes. 
We are increasing work for us by having to maintain _another_ conditional execution conditions for vignettes. 

Only use pipes in README, which are also included in CRAN, to showcase that easystats functions will play happily with them.
