### ISSUE TITLE
Warning message: Could not find Sum-of-Squares for the (Intercept) in the ANOVA table. 

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#318]
Following easystats/easystats#338, I would like to get rid of all warnings in tests for `report`. I need help from someone knowledgeable on the matter to help clarify whether the warning below is expected (therefore to be suppressed with `verbose = FALSE`) or unexpected (therefore to be fixed). This is the first example in our tests for `report.aov.R`.

``` r
library(report)
model <- anova(lm(Sepal.Width ~ Species, data = iris))
r1 <- report(model)
#> Warning: Could not find Sum-of-Squares for the (Intercept) in the ANOVA table.
```

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Somewhere, you’re asking for `include_intercept = TRUE` but the ANOVA table is type 1 and does not contain SS for the intecept:

``` r
(model <- anova(lm(Sepal.Width ~ Species, data = iris)))
#> Analysis of Variance Table
#> 
#> Response: Sepal.Width
#>            Df Sum Sq Mean Sq F value    Pr(>F)    
#> Species     2 11.345  5.6725   49.16 < 2.2e-16 ***
#> Residuals 147 16.962  0.1154                      
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

effectsize::eta_squared(model, include_intercept = TRUE)
#> Warning: Could not find Sum-of-Squares for the (Intercept) in the ANOVA table.
#> For one-way between subjects designs, partial eta squared is equivalent
#>   to eta squared. Returning eta squared.
#> # Effect Size for ANOVA
#> 
#> Parameter | Eta2 |       95% CI
#> -------------------------------
#> Species   | 0.40 | [0.30, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].
```

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
Thanks @mattansb. That's true. `include_intercept = TRUE` is forced everywhere and its not a parameter the user can change at this time. So that kind of creates problems for our examples since I understand by default base R and `easystats` use type 1 SS.

What should that look like for `report` ideally you think?

(a) We add an argument to specify whether to include the intercept or not (and adapt as appropriate in our examples/testing). If so, should we default to TRUE or FALSE?
(b) We could force it to FALSE always instead of TRUE.
(c) We could keep it as is and silence it.
(d) Or do you think there would be a way to detect this automatically for the user and set it to TRUE or FALSE as appropriate?

**Comment by rempsyc** [comment]
@mattansb any idea why `insight::has_intercept()` returns TRUE even though it's ANOVA type I?

``` r
model <- aov(lm(Sepal.Width ~ Species, data = iris))
insight::has_intercept(model)
#> [1] TRUE
```

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Perhaps there is an alternative solution to `insight::has_intercept()`. Is there any way to detect automatically the ANOVA type so I could code around that? Doesn't seem to appear in attributes.

**Comment by mattansb** [comment]
I think reporting the intercept is quite meaningless in ANOVA, so I would omit it completly. I don't know why we have it "on" by default here - @DominiqueMakowski ?

> @mattansb any idea why `insight::has_intercept()` returns TRUE even though it's ANOVA type I?

This is because the **model** has an intercept, but the default ANOVA **table** does not.

``` r
model <- aov(lm(Sepal.Width ~ Species, data = iris))

coef(model)
#>       (Intercept) Speciesversicolor  Speciesvirginica 
#>             3.428            -0.658            -0.454

anova(model)
#> Analysis of Variance Table
#> 
#> Response: Sepal.Width
#>            Df Sum Sq Mean Sq F value    Pr(>F)    
#> Species     2 11.345  5.6725   49.16 < 2.2e-16 ***
#> Residuals 147 16.962  0.1154                      
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

<sup>Created on 2023-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
