### ISSUE TITLE
Update author list for citations

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#322]
What is the correct order of authors? We have different versions right now:

``` r
library(report)

citation("report")
#> 
#> To cite in publications use:
#> 
#>   Makowski, D., Ben-Shachar, M.S., Patil, I., Lüdecke, D., & Thériault,
#>   R. (2020). Automated Results Reporting as a Practical Tool to Improve
#>   Reproducibility and Methodological Best Practices Adoption. CRAN.
#>   Available from https://github.com/easystats/report. doi: .
#> 
#> A BibTeX entry for LaTeX users is
#> 
#>   @Article{,
#>     title = {Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption},
#>     author = {Dominique Makowski and Mattan S. Ben-Shachar and Indrajeet Patil and Daniel Lüdecke and Rémi Thériault},
#>     year = {2021},
#>     journal = {CRAN},
#>     url = {https://github.com/easystats/report},
#>   }

cite_easystats(packages = "report")
#> - Makowski, D., Lüdecke, D., Ben-Shachar, M. S., Patil, I., Wiernik, B. M.,
#>     & Thériault, R. (2022). report: Automated reporting of results and
#>     statistical models (0.5.5.3) [R package].
#>     https://CRAN.R-project.org/package=report (Original work published
#>     2021)

# in easystats_bib.yaml, we have 
# "author:
# - family: Makowski
#  given: Dominique
#  - family: Lüdecke
#  given: Daniel
#  - family: Ben-Shachar
#  given: Mattan S.
#  - family: Patil
#  given: Indrajeet
#  - family: Wiernik
#  given: Brenton M.
#  - family: Thériault
#  given: Rémi"
```

<sup>Created on 2023-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Does this need to be updated? How is the order of authors determined? Is it based on the order in https://github.com/easystats/report/graphs/contributors or something else?

**Comment by rempsyc** [comment]
@IndrajeetPatil I would like to update this before sending to CRAN. What is the usual `easystats` rule for determining authorship order? Or is it ok as is?

**Comment by bwiernik** [comment]
I would keep Dom first for continuity of "Makowski et al" citations, then put Remi next, then the others in whichever order

**Comment by rempsyc** [comment]
If anything, I was thinking more something like:

``` r
get_contributions <- function(repo, user = "easystats") {
  paste0("https://github.com/", user, "/", repo, "/graphs/contributors-data") |> 
    httr2::request() |> 
    httr2::req_headers("x-requested-with" = "XMLHttpRequest",
                       accept = "appliacation/json") |> 
    httr2::req_perform() |> 
    httr2::resp_body_json(simplifyVector = TRUE, check_type = FALSE) |> 
    tidyr::unnest(everything()) |> 
    dplyr::group_by(username = stringr::str_remove(path, "/")) |> 
    dplyr::summarise(across(a:c, sum)) |> 
    dplyr::arrange(dplyr::desc(a), dplyr::desc(d), dplyr::desc(c)) |>
    dplyr::rename(added = a, deleted = d, commit = c) |> 
    as.data.frame()
}

data <- get_contributions("report")

order_authors <- function(data) {
  data$score <- data$added + abs(data$deleted) + data$commit
  data <- data[order(data$score, decreasing = TRUE), ]
  data <- data[data$score >= 1000, ]
  cat(toString(data$username), "\n\n")
  data
}

order_authors(data)
#> DominiqueMakowski, strengejacke, IndrajeetPatil, rempsyc, mattansb, bwiernik
#> 
#>            username  added deleted commit  score
#> 1 DominiqueMakowski 203778  148154    325 352257
#> 3      strengejacke   5129   38164    223  43516
#> 2    IndrajeetPatil  15082   10513    159  25754
#> 4           rempsyc   3427    2938     14   6379
#> 6          mattansb   1009     603     14   1626
#> 5          bwiernik   1371     156     11   1538
```

What do you think? If you like this approach, should I reduce dependencies and make these actual `easystats` functions? We don’t have to follow this rigidly but it can give a rough and quick idea as to what is going on and going beyond simply the number of commits. There probably would be a way also to update authorship order automatically in a GHA workflow (probably not practical though for various reasons).

<sup>Created on 2023-01-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
I don’t think the number of commits is a good metric for contributions because different developers have different preferences for merge strategy. For example, I always squash and merge. This means that even if your PR contained 25 commits, it only counts as a single commit. If someone else doesn’t do that, their 25 commits show up as they are in the project git history. You can’t say the former counts for less than the latter. 

A better metric, if that’s what you are after, is additions – deletions. 

That said, we have been quite relaxed about authorship orders in easystats packages and have even changed author orders post-publication.

I have no problem if you move to the second author position in `DESCRIPTION` since you are the one maintaining and actively contributing to it and will continue to do so.

We can revisit this issue when we start working on the JOSS publication. I guess Dom will be the first author, but maybe it makes sense for the maintainer to be the last/senior author.

**Comment by rempsyc** [comment]
> I don’t think the number of commits is a good metric for contributions because different developers have different preferences for merge strategy.

True, good point. Although in the above formula the number of commits is almost worthless (only the equivalent of the lines of code), I'll remove it. Lines of codes added and removed do make sense to me since they generally represent real work, but of course it is not perfect and probably need human validation.

> That said, we have been quite relaxed about authorship orders in easystats packages and have even changed author orders post-publication.

In this sense, I think it natural that author order evolves (separately from the publication) as contribution proportions change since contrary to a static publication, it is more of a living project. And to me I don't know if being maintainer should impact authorship (or significantly so) relative to contributed code. I suppose there is indeed associated invisible work that won't appear in code lines, such as tagging, assigning, and reviewing PRs and issues, etc., so could be taken into account at some point. But clearly Indra and Daniel you have put a ton of work into `report` so I am comfortable being 4th until my contributions go beyond that.

> We can revisit this issue when we start working on the JOSS publication. I guess Dom will be the first author, but maybe it makes sense for the maintainer to be the last/senior author.

I am happy to change it to the order I mentioned above for now, but of course if somebody feels it should be different, please let me know.

**Comment by strengejacke** [comment]
I'm fine with changing the order. :-)

**Comment by bwiernik** [comment]
My general perspective is the maintainer can adjust the author order as feels appropriate to them.

**Comment by DominiqueMakowski** [comment]
Yeah it is a complicated issue. Too much changes is not necessarily good for referencing, but being too frozen is also not good to reflect the dynamic nature of the object. 
> maybe it makes sense for the maintainer to be the last/senior author.

A soft rule/guideline could be something like that yes, that the maintainer is "senior author" if different from the "creator" (which is itself a loose term). Or co-first, but that gets complicated for the CRAN objects. 

That said, I also agree with leaving a fair amount freedom to the maintainers to shuffle as they feel appropriate.
