### ISSUE TITLE
Could we keep the git tag name consistent?

### ISSUE THREAD

**Issue by hubutui** [easystats/report#336]
Just make it `v$pkgver` or `$pkgver`. It helps a lot for automatically creating pkg for [BioArchLinux](https://github.com/BioArchLinux/Packages/blob/d220f0791a3efd30371aafdccbde25ba3af8653b/BioArchLinux/r-report/PKGBUILD#L33). Thanks.

**Comment by rempsyc** [comment]
I'm sorry, I'm not familiar with git tag names. What are they? And where on report's GitHub does this refer to (an example of current behaviour would be helpful)

**Comment by rempsyc** [comment]
On the document you linked, there seems to be a different maintainer for the linux bio archive:

> Maintainer: Hu Butui <hot123tea123@gmail.com>

Maybe this is the person you should contact for this issue? I don't think we provide official support outside of GitHub and CRAN.

**Comment by bwiernik** [comment]
When you make a "Release" on GitHub, you give a name for it. That's a "tag" that can be referenced/linked to like a branch or commit hash. 

We've been inconsistent with including a "v" before the release number on the tag. We should be sure to always do so

**Comment by strengejacke** [comment]
I think we recently started to use just version numbers:
https://github.com/easystats/parameters/tags
https://github.com/easystats/insight/tags

Latest datawizard tag has a v though:
https://github.com/easystats/datawizard/tags

@easystats/maintainers

**Comment by rempsyc** [comment]
I see now. To make the release, I simply used `usethis::use_github_release()`, and went for the default. So I think by default `usethis::use_github_release()` uses the v for the tag. Is that possible?

https://github.com/r-lib/usethis/blob/HEAD/R/release.R#L152
https://github.com/r-lib/usethis/blob/HEAD/R/release.R#L248

So I think it makes sense to be consistent and use the `usethis` default to minimize mistakes. What do you think? Do we all agree to keep v before version then?

**Comment by strengejacke** [comment]
I don't really mind. If I would run the above linked script, I would prefer no "v", because the filename `${_pkgname}_${pkgver}` looks ugly with a "v" in it before the version number ;-)

**Comment by rempsyc** [comment]
Sure, but it is extra work for the maintainers if we have to manually overwrite default values. As such, I suspect most other packages will have the v, so in a workflow it will be easier to code assuming the v. And I think it is better practice to follow what the majority of other packages do (or will do if it's not the majority yet).

**Comment by bwiernik** [comment]
In my experience, the vast majority of packages and other software use "v" in version names
