### ISSUE TITLE
Preserve parallelization settings from `brmsfit` objects when standardizing/refitting `brms` models

### ISSUE THREAD

**Issue by gserapio** [easystats/report#339]
Love this ecosystem of packages, thanks to the contributors for all that they do!

**Context**
Currently, when running `report()` on `brmsfit` objects, parameters are standardized and the model is refit for interpretation. However, many `brms` models take a long time to fit and benefit a ton from parallelization. By default, it seems that refitting is done sequentially with minimal within-chain parallelization:

`Running MCMC with 4 sequential chains, with 2 thread(s) per chain...`

My rough traceback is: `report::report.lm()` -> `report_effectsize.lm()` -> `effectsize::effectsize()` (line 74 [here](https://github.com/easystats/report/blob/main/R/report.lm.R)) -> `parameters::standardize_parameters()` (line 152 [here](https://github.com/easystats/effectsize/blob/main/R/effectsize.R)) ?

**Describe the solution you'd like**
Would there be a way to use the original parallelization settings (`cores`, `threads`) when standardizing `brmsfit` objects?

**How could we do it?**
Maybe this could be a new argument for `report()`: `original_parallel_settings = TRUE` that passes the original settings all the way to `parameters::standardize_parameters()`.

**Comment by DominiqueMakowski** [comment]
By default re-fitting should re-use the same parameters since it uses `updzte()` if I'm not mistaken, I'm surprised it isn't already the case 🤔

**Comment by gserapio** [comment]
> By default re-fitting should re-use the same parameters since it uses `updzte()` if I'm not mistaken, I'm surprised it isn't already the case 🤔

Good point, that is surprising! For me, it seems to be preserving the settings for `threads` but not `cores`. I'll try to get a reprex up at some point.

**Comment by bwiernik** [comment]
I think I encountered not preserving those settings when using `update()` itself a while back. You should open an issue on the brms GitHub repo--this would be an issue there.

**Comment by bwiernik** [comment]
Closing because this is an upstream issue with brms
