### ISSUE TITLE
model metrics don't match between model_text_performance_bayesian() and model_performance()

### ISSUE THREAD

**Issue by brandondey** [easystats/report#36]
`report()` on a mixed bayesian model doesn't report text on the model's explanatory performance from the internal `model_text_performance_bayesian()`. "The model's explanatory power is...."

It looks like this is because the names(performance) generated from `performance::model_performance() `don't match the conditions inside `model_text_performance_bayesian()`.

E.g.:
```
table_performance_0 <- performance::model_performance(b_mod, performance_metrics = "all")
model_text_performance_bayesian(table_performance_0)
```
produces 
```
$text
[1] ""

$text_full
[1] ""
```
because `names(table_performance_0)` does not have column names "R2_Median" or "R2_marginal_Median", but rather "R2" and "R2_marginal". 

Changing the names produces (nearly) expected text results.
```
names(table_performance_0)[6] <- "R2_Median"
names(table_performance_0)[8] <- "R2_marginal_Median"
model_text_performance_bayesian(performance = table_performance_0)
```
```
$text
[1] "The model's explanatory power is substantial (R2's median = 0.85, LOO adj. R2 = 0.85). Within this model, the explanatory power related to the fixed effects alone (marginal R2's median) is of 0.78."

$text_full
[1] "The model's total explanatory power is substantial (R2's median = 0.85, MAD = , 90% CI [, ], LOO adj. R2 = 0.85). Within this model, the explanatory power related to the fixed effects alone (marginal R2's median) is of 0.78 (MAD = , 90% CI [, ])."
```
I say nearly becuase MAD is still missing from the performance table. `model_text_performance_bayesian()` expects to find columns in the performance table called "R2_marginal_MAD" and "R2_marginal_CI_high"

Unless I'm missing something, which is totally possible.

**Comment by DominiqueMakowski** [comment]
#37
