### ISSUE TITLE
objects of class [Date] are not supported by report_table()

### ISSUE THREAD

**Issue by Chinca-lang** [easystats/report#373]
Please consider including vectors of class [Date]. They could be summarised as time span or frequency or like factor variables.

**Comment by rempsyc** [comment]
For future reference could you provide a reprex to show current behaviour? Thanks!

**Comment by Chinca-lang** [comment]
dear all, sorry for not being clear before. Let me know if this code can clarify the issue. I've just used the first two variable of my df. 
> str(example1)
'data.frame':	572 obs. of  2 variables:
 $ ID  : Factor w/ 26 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ date: Date, format: "2020-08-03" "2020-08-25" ...

and if I summarise it is: 
> summary(example1)
       ID           date           
 1      : 22   Min.   :2020-08-03  
 2      : 22   1st Qu.:2021-02-08  
 3      : 22   Median :2021-07-05  
 4      : 22   Mean   :2021-06-24  
 5      : 22   3rd Qu.:2021-11-29  
 6      : 22   Max.   :2022-05-26  
 (Other):440        

If I call report I get this message:
> report::report(example1)
Error: Oops, objects of class [Date] are not supported (yet) by report_table() :(

> Want to help? Check out https://easystats.github.io/report/articles/new_models.html

Thanks for your support!

**Comment by strengejacke** [comment]
One of your suggestions was treating dates like factors, which is what _report_ now does with the recent commits. We could also change the behaviour to something else, but I rarely work with dates, so I'm not sure what's the most appropriate way to report date-variables.

**Comment by Chinca-lang** [comment]
cool, thanks a lot for your work!
I didn't understandbbefore because for some reason it seems not working on my version report_0.5.7
I've tried to reproduce your code:
> set.seed(123)
> x <- sample(seq(as.Date("1999/01/01"), as.Date("1999/01/05"), by = "day"), 30, replace = TRUE)
> report::report(x)
Error: Oops, objects of class [Date] are not supported (yet) by report() :(
Want to help? Check out https://easystats.github.io/report/articles/new_models.html

I've checkd x and it is:
> str(x)
 Date[1:30], format: "1999-01-03" "1999-01-03" "1999-01-02" "1999-01-02" "1999-01-03" "1999-01-05" "1999-01-04" ...

do you have any suggestion?

**Comment by strengejacke** [comment]
For now, it's only available in the GitHub version of _report_. You can install it, after installing the _easyverse_ package, by running `easystats::install_latest()`.

**Comment by Chinca-lang** [comment]
awesome! thanks a lot
