### ISSUE TITLE
report dataset with date 0.5.8 good news but how to install

### ISSUE THREAD

**Issue by genghiskhanofnz** [easystats/report#376]
Hi there, 0.5.8 news is big for me accepting date as factor.
When will it be on CRAN?
Thanks.
G

**Comment by strengejacke** [comment]
You can easily install the latest versions of the _easystats_ packages by

1. installing the _easystats_ package, if you haven't done yet: `install.packages("easystats", dependencies = TRUE)` - you only need to do this once.
2. run `easystats::install_latest()`

Then you don't need to wait for CRAN versions.

**Comment by genghiskhanofnz** [comment]
@strengejacke 
I did your advice.
Still 0.5.7.9, not 0.5.8

> packageVersion('report')
[1] ‘0.5.7.9’

Why not installing 0.5.8?
Please advice.
G

**Comment by strengejacke** [comment]
That's the latest version, the news just names the planned version number, not the actual package version. It should already work that dates are treated as factors.

**Comment by genghiskhanofnz** [comment]
@strengejacke 
I tested and it works like a charm.
Thank you.

How to convert the report() results into a nice table with your easystats packages?
G

> library(report)
> report(theatre2)
The data contains 4386 observations of the following 6 variables:

  - time: 21 entries, such as 1/02/2019 (4.90%); 1/12/2019 (4.90%); 1/05/2020 (4.88%) and 18 others (0 missing)
  - prices: n = 4386, Mean = 35.03, SD = 1.00, Median = 35.03, MAD = 1.01, range: [31.56, 38.42], Skewness = 6.22e-03, Kurtosis = 0.01, 0% missing
  - quantities: n = 4386, Mean = 153.97, SD = 327.18, Median = 22.40, MAD = 31.18, range: [2.12e-03, 3437.96], Skewness = 4.12, Kurtosis = 22.85, 0% missing
  - prodID: n = 4386, Mean = 2.99e+05, SD = 1.59e+05, Median = 4.01e+05, MAD = 7226.19, range: [14215, 407860], Skewness = -0.89, Kurtosis = -1.13, 0% missing
  - retID: n = 4386, Mean = 1461.59, SD = 869.77, Median = 1032.00, MAD = 1.48, range: [1030, 3220], Skewness = 1.53, Kurtosis = 0.33, 0% missing
  - description: 6 entries, such as hbt (28.00%); gensurg (21.57%); colorectal (18.29%) and 3 others (0 missing)

**Comment by strengejacke** [comment]
I think this is covered in the docs:
https://easystats.github.io/report/articles/report_table.html

**Comment by strengejacke** [comment]
Closing, since initial issue is resolved
