### ISSUE TITLE
What's the best way to provide appropriate attribution/citation?

### ISSUE THREAD

**Issue by emstruong** [easystats/report#383]
**Question and context**
Based on the README, it seems that the package should be cited in manuscripts, which makes sense to me. 

What I'm wondering is whether there's any need to put any further comments in the manuscript beyond merely stating that the package was used. (For example, "the t-tests here are reported based on the wording of the R package _report_.")

For example, a different project that also uses automated reporting [fmriprep](https://fmriprep.org/en/stable/index.html#citation)--[elaborated here](https://www.nipreps.org/intro/transparency/#citation-boilerplates)--has a 'citation boilerplate' where they automatically generate a methods paragraph for how their pre-processing pipeline functioned.

**Comment by bwiernik** [comment]
You can run: `report::cite_easystats()` to see the preferred citations. 

You can cite either just the easystats umbrella package or the packages and articles for all of individual easystats packages, whichever you prefer

**Comment by DominiqueMakowski** [comment]
we don't have a template paragraph to specifically mention which stats report were generated with `report`.

Personally, as @bwiernik mentioned, I just list the packages used in the methods or results section with citations, and then the accompanying R code (in which `report` is used) is made available alongside the paper
