### ISSUE TITLE
get rid of dplyr

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#39]
I think we should avoid using dplyr in report, and looking at the code, I think this is easy to do. I can work on `report.data.frame()`...

**Comment by DominiqueMakowski** [comment]
If I recall correctly, the main blocker for that was `report.grouped_df`

**Comment by strengejacke** [comment]
Probably, but we also have advanced our R skills the past months, so... 💪

**Comment by DominiqueMakowski** [comment]
true dat 🚀

**Comment by strengejacke** [comment]
I think behaviour has changed since dplyr 0.8.0, which was released mid of Feb 19. We can recycle this code here: https://github.com/strengejacke/sjmisc/blob/master/R/reshape_helpers.R#L65

**Comment by strengejacke** [comment]
closing in favor of https://github.com/easystats/report/issues/63
