### ISSUE TITLE
CRAN submission revedep check failed (*** Strong rev. depends ***: easystats SqueakR)

### ISSUE THREAD

**Issue by rempsyc** [easystats/report#409]
```
Dear maintainer,

package report_0.5.8.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/report_0.5.8_20231205_190732/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/report_0.5.8_20231205_190732/Debian/00check.log>
Status: 1 NOTE
*** Strong rev. depends ***: easystats SqueakR
```

Error is:
``` r
Mismatches for apparent methods not registered:
.report_sample_row:
  function(x, digits, ...)
.report_sample_row.factor:
  function(x, column, weights, digits, ci, ci_method, ci_correct, n,
           ...)

.report_sample_row:
  function(x, digits, ...)
.report_sample_row.character:
  function(x, column, weights, digits, ci, ci_method, ci_correct, n,
           ...)

.report_sample_row:
  function(x, digits, ...)
.report_sample_row.numeric:
  function(x, column, centrality, weights, digits, n, ...)
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```

https://win-builder.r-project.org/incoming_pretest/report_0.5.8_20231205_190732/Windows/00check.log

**Comment by rempsyc** [comment]
First time I get a revedep check fail. What is the procedure here? Do I need to contact the author to tell them to update their package to CRAN before we resubmit?

**Comment by strengejacke** [comment]
Doesn't look like a revdep-issue. Should be fixed in https://github.com/easystats/report/commit/b36b65723eedaaea665997d70ebc6a6b7d646b01.

**Comment by strengejacke** [comment]
(quickly merging a PR, so it's included in the next submission :-)

**Comment by rempsyc** [comment]
Local revdepcheck was OK after this change (thanks!), will resubmit

**Comment by rempsyc** [comment]
Dear maintainer,
 
thanks, package report_0.5.8.tar.gz is on its way to CRAN.

**Comment by strengejacke** [comment]
> Local revdepcheck was OK

Yeah, but I bet the issue was the S3 mismatch, and not related to reverse dependencies. It's just strange that GH workflows did not catch this error. Maybe we would have found it when submitting to win-builder.

**Comment by rempsyc** [comment]
Well I had ran `devtools::check_win_devel()` and there were no issues, but I'm glad we fixed it!
