### ISSUE TITLE
report_table() fully markdown compatible?

### ISSUE THREAD

**Issue by petzi53** [easystats/report#415]
I just learned from your marvelous package. Trying out the `report_table()` function, I wonder if it wouldn't be nice to get a table completely compatible with Markdown. What I mean: Instead of the following snippet:

```
#> Parameter1 | Parameter2 |     r |         95% CI | t(30) |      p
#> -----------------------------------------------------------------
#> mtcars$mpg |  mtcars$wt | -0.87 | [-0.93, -0.74] | -9.56 | < .001
```
I would like to have the following minor changes:

```
#> Parameter1 | Parameter2 |     r |         95% CI | t(30) |      p
#> -----------|------------|-------|----------------|-------|--------------
#> mtcars$mpg |  mtcars$wt | -0.87 | [-0.93, -0.74] | -9.56 | < .001
```

The advantage of this small change? It would allow with some R chunk options to interpret the output as a Markdown table:
The options I am referring are:

```
#| comment: ''
#| results: markup
```
With an extra argument in the function, you could provide both options. 

Please tell me if this is a sound idea, or if I have misunderstood completely the purpose of the function.

**Comment by bwiernik** [comment]
Can you clarify why the extra dashes in the second example affects markdown parsing? The p value column should be right-aligned, which the current output is

**Comment by strengejacke** [comment]
Thanks, can be closed now? Else, feel free to re-open.
