### ISSUE TITLE
bayes factors in `bayesfactor_*` report

### ISSUE THREAD

**Issue by mattansb** [easystats/report#42]
*originally from #38*

- `bayesfactor_inclusion`
    - [x] `text` - only results.
    - [x] `text_full` - Give full explanation about model averaging + posterior probability.
    - [x] `table` - basically `as.data.frame`
    - [x] `table_full` - ***same as `table`??***
    - [x] docs...
    - [x] tests...
- `bayesfactor_models`
    - [x] `text` - method + denominator + {best + worst model}
    - [x] `text_full` - with BF computation method + all models.
    - [x] `table` - basically `as.data.frame`
    - [x] `table_full` - give also "BF01 compared to best model` column.
    - [x] docs...
    - [x] tests...
- `bayesfactor_parameters`
    - [ ] `text` - what null (once), BF for each, by name.
    - [ ] `text_full` - ***same as `text`??***
    - [ ] `table` - basically `as.data.frame` + row for null and side
    - [ ] `table_full` - ***same as `table`??***
    - [ ] docs...
    - [ ] tests...
- `bayesfactor_restricted`
    - [ ] `text` - ***???***
    - [ ] `text_full` - ***???***
    - [ ] `table` - basically `as.data.frame`
    - [ ] `table_full` - ***same as `table`??***
    - [ ] docs...
    - [ ] tests...

### Notes to self:
- Should use `interpret_bf` internally for `text`, with arg `rules`.

**Comment by mattansb** [comment]
``` r
library(bayestestR)
library(report)

mo0 <- lm(Sepal.Length ~ 1, data = iris)
mo1 <- lm(Sepal.Length ~ Species, data = iris)
mo2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
mo3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

BFmodels <- bayesfactor_models(mo1, mo2, mo3, denominator = mo0)
inc_bf <- bayesfactor_inclusion(BFmodels, prior_odds = c(1,2,3), match_models = TRUE)

bf_report <- report(inc_bf)

to_table(bf_report) # same for both full = FALSE / TRUE
#> Terms                             | Pr(prior) | Pr(posterior) | Inclusion BF
#> ----------------------------------------------------------------------------
#> Species                           |     0.429 |         0.946 |    3.895e+55
#> Petal.Length                      |     0.286 |         0.946 |    6.891e+26
#> Species:Petal.Length              |     0.429 |         0.054 |        0.038
#>                                   |           |               |             
#> Across matched models only,       |           |               |             
#> with custom prior odds (1, 2, 3). |           |               |

to_text(bf_report, full = FALSE)
```
`We found extreme evidence (BF > 999) in favour of including Species; extreme evidence (BF > 999) in favour of including Petal.Length; strong evidence (BF = 0.04) against including Species:Petal.Length.`
```R
to_text(bf_report, full = TRUE)
```
`Bayesian model averaging (BMA) was used to obtain the average evidence for each predictor. Since each model has a prior probability (here we used subjective prior odds of 1, 2, 3), it is possible to sum the prior probability of all models that include a predictor of interest (the prior inclusion probability), and of all models that do not include that predictor (the prior exclusion probability). After the data are observed, we can similarly consider the sums of the posterior models’ probabilities to obtain the posterior inclusion probability and the posterior exclusion probability. The change from prior to posterior inclusion odds is the Inclusion Bayes factor. For each predictor, averaging was done only across models that did not include any interactions with that predictor; additionally, for each interaction predictor, averaging was done only across models that contained the main effect from which the interaction predictor was comprised. This was done to prevent Inclusion Bayes factors from being contaminated with non-relevant evidence (see Mathot, 2017). We found extreme evidence (BF > 999) in favour of including Species; extreme evidence (BF > 999) in favour of including Petal.Length; strong evidence (BF = 0.04) against including Species:Petal.Length.`

**Comment by strengejacke** [comment]
@mattansb what's the status of this issue?

**Comment by mattansb** [comment]
Nothing has changed... If you're looking for an initial submit, this is probably good enough for now (with inclusion + model).

Parameter-wise reporting has been implemented else where I think? Maybe in `describe_posterior`'s reporting? At the very least I remember working on something like that with Dom.

**Comment by DominiqueMakowski** [comment]
that is in, I think

**Comment by mattansb** [comment]
Only `bf_models` and `bf_inclusion` have their own methods I think.
Are `bf_parameters` included in Bayesian reporting?

**Comment by DominiqueMakowski** [comment]
no, Bayesian reporting is in its absolute minimal state 😅 and will need a lot of improvement

**Comment by DominiqueMakowski** [comment]
but at least the API is now simpler so it should be simpler to fix / improve

**Comment by mattansb** [comment]
👍
