### ISSUE TITLE
problems using group_by with cor.test report

### ISSUE THREAD

**Issue by mihinduk** [easystats/report#424]
**Describe the bug**
I am unable to use tidyverse group_by and then pass data to corr.test and generate a report.

Error in match.arg(alternative) : 
  'arg' must be NULL or a character vector

**To Reproduce**
Steps to reproduce the behaviour:
Here is the bug reproduced with the iris dataset:
iris %>%
  group_by(Species) %>%
  cor.test(iris$Sepal.Length, iris$Sepal.Width) %>%
  report() %>%
  as.data.frame()

**Expected behaviour**
Pearson's product-moment correlation

Parameter1        |       Parameter2 |     r |        95% CI | t(148) |     p
-----------------------------------------------------------------------------
iris$Sepal.Length | iris$Sepal.Width | -0.12 | [-0.27, 0.04] |  -1.44 | 0.152

Alternative hypothesis: two.sided

BUT per Species

**Screenshots**

<img width="400" alt="Screenshot 2024-04-03 at 1 09 49 PM" src="https://github.com/easystats/report/assets/55006605/36859570-5f1e-499f-a31d-20b95d5e5142">

**Specifications (please complete the following information):**
packageVersion("rstatix")
[1] ‘0.7.2’
packageVersion("stats")
[1] ‘4.2.2’
packageVersion("easystats")
[1] ‘0.7.1’
packageVersion("report")
[1] ‘0.5.8’

**Comment by bwiernik** [comment]
`cor.test()` doesn't support grouped data frames. You would need to use a workflow that splits the data into separate frames by Species, such as with `split()` and `lapply()`. Or easier, use the `correlation::correlation()` function, which does support grouped data frames.
