### ISSUE TITLE
Missing citation for Allie Brosh's "All the Things" image

### ISSUE THREAD

**Issue by deborah-chasman** [easystats/report#428]
**Describe the bug**
I was not able to find a citation for the image "allthethings.jpg" in the package documentation: https://easystats.github.io/report/#report-all-the-things

The image is from a popular cartoon by Allie Brosh in her blog Hyperbole and a Half.
As per the artist's FAQ (https://hyperboleandahalf.blogspot.com/p/faq_10.html), her images are free to re-use with attribution.

**To Reproduce**
n/a

**Expected behaviour**
When the bug is fixed, the image would be accompanied by a link to the original blog post and an attribution that it was drawn by Allie Brosh. Here's the original blog post:
https://hyperboleandahalf.blogspot.com/2010/06/this-is-why-ill-never-be-adult.html

**Screenshots**

![image](https://github.com/easystats/report/assets/9661893/ecda1f70-4996-4961-90e2-2ab06b4a8c4d)

**Specifications (please complete the following information):**
 - Package Version 0.5.8
 - GitHub README viewed 2024-05-01

Thank you for making `report` available! It's a great utility.

**Comment by strengejacke** [comment]
@DominiqueMakowski @rempsyc

**Comment by strengejacke** [comment]
Thanks, I guess this is fixed now?
