### ISSUE TITLE
Fix contrast errors coming from a customization that only the report website template is using

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#431]
Only `{report}` customizes colors for navbar entries in the pkgdown website, which are not accessibility-friendly.

You can look at contrast errors here:
 
https://wave.webaim.org/report#/https://easystats.github.io/report/

**Comment by IndrajeetPatil** [comment]
This has become irrelevant with devel-pkgdown, and dark mode.

**Comment by rempsyc** [comment]
If I understand correctly, the contrasts are OK in dark mode, but the problem persists when using light mode? So it would still make sense to change the colour choice? Would you recommend not customizing colours so that all easystats packages share exactly the same `pkgdown` style?
