### ISSUE TITLE
Report fails when using a valid syntax in kruskal.test() and wilcox.test()

### ISSUE THREAD

**Issue by gorkang** [easystats/report#466]
In tests such as `kruskal.test()` or `wilcox.test()`, you can perform the same analysis in two different ways, for example:

``` r
x1 <- kruskal.test(airquality$Ozone ~ as.factor(airquality$Month))
x1
#> 
#>  Kruskal-Wallis rank sum test
#> 
#> data:  airquality$Ozone by as.factor(airquality$Month)
#> Kruskal-Wallis chi-squared = 29.267, df = 4, p-value = 6.901e-06

x2 <- kruskal.test(Ozone ~ as.factor(Month), data = airquality)
x2
#> 
#>  Kruskal-Wallis rank sum test
#> 
#> data:  Ozone by as.factor(Month)
#> Kruskal-Wallis chi-squared = 29.267, df = 4, p-value = 6.901e-06

```

But when `report()`, only works with the first syntax:  

``` r
# Works
report::report(x1) 
#> Warning: Missing values detected. NAs dropped.
#> Effect sizes were labelled following Field's (2013) recommendations.
#> 
#> The Kruskal-Wallis rank sum test testing the difference in ranks between
#> airquality$Ozone and as.factor(airquality$Month) suggests that the effect is
#> statistically significant, and large (Kruskal-Wallis chi2 = 29.27, p < .001;
#> Epsilon squared (rank) = 0.25, 95% CI [0.17, 1.00])

# Fails
report::report(x2)
#> Error: Unable to retrieve data from htest object.
#>   Try using 'rank_epsilon_squared()' directly.
```

<sup>Created on 2024-11-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
As the error states, the data cannot be recovered - since it is required to compute the effect size, the report fails. This is due to the flimsy htest class that does not store enough information. We recommend *not* using formula syntax for htest functions, and passing vectors directly.

**Comment by gorkang** [comment]
Maybe it would be worth it to include a sensible error message to point out that report does not work with the formula syntax? Cheers.

**Comment by mattansb** [comment]
As far as I can tell, we have no way of knowing post-hoc why the data was not recovered, so we have no other option but to give a vague error. But perhaps this should be included in the `report(<htest>)` docs - @rempsyc?

**Comment by rempsyc** [comment]
@gorkang as Mattan pointed out, htest objects do not contain the original data so it is not possible to recover it. However, you can provide the original data directly to report:

``` r
x2 <- kruskal.test(Ozone ~ as.factor(Month), data = airquality)
report::report(x2, data = airquality)
#> Warning: Missing values detected. NAs dropped.
#> Effect sizes were labelled following Field's (2013) recommendations.
#> 
#> The Kruskal-Wallis rank sum test testing the difference in ranks between Ozone
#> and as.factor(Month) suggests that the effect is statistically significant, and
#> large (Kruskal-Wallis chi2 = 29.27, p < .001; Epsilon squared (rank) = 0.25,
#> 95% CI [0.15, 1.00])
```

<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
In version 0.5.9.1 available from GitHub, there should now be a clearer warning when the data argument is not available and not provided to report:

``` r
x2 <- kruskal.test(Ozone ~ as.factor(Month), data = airquality)
report::report(x2)
#> In the report() function, for htest objects, you can try providing the
#>   data argument manually, e.g., report(x, data = data).
#> Error: Unable to retrieve data from htest object.
#>   Try using 'rank_epsilon_squared()' directly.
```

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
Closing this issue as I believe we have addressed your concern :)
