### ISSUE TITLE
Can't calculate log-loss. Error: 'format_ci' is not an exported object from 'namespace:parameters'

### ISSUE THREAD

**Issue by cesterwo1056** [easystats/report#59]
I'm not sure if this is an error with the report() function or something with my data but here it is:

When trying to get report to summarize a glm object, I get the following error:

```
Can't calculate log-loss.
Error: 'format_ci' is not an exported object from 'namespace:parameters'

```
Here is what I'm running:

```
glm.out <- glm(data=data, survived ~ sex, family=binomial)

report(glm.out)
```
I'm using some basic titanic data for learning purposes and trying to run a logistic regression on sex vs. survived and consider this to be binomial data. 

---
I guess, I'm not sure if it is just me or if it is the report() package.

**Comment by strengejacke** [comment]
Should be fixed now, please check the lastest master-branch on GitHub.

**Comment by strengejacke** [comment]
_bump_

**Comment by cesterwo1056** [comment]
Works beautifully now. Sorry for the dlay in trying it again!
