### ISSUE TITLE
using jamovi with report

### ISSUE THREAD

**Issue by sbalci** [easystats/report#60]
Hi,

I have implanted report package into a jamovi module.

With your permission I would like to submit it to be included in the module when I make final adjustments.

Code is here: https://github.com/sbalci/ClinicoPathJamoviModule/blob/master/R/report.b.R

Best wishes

Here is how it looks like:
![jamovi-and-R-report](https://user-images.githubusercontent.com/7208830/73919735-27baaa00-48d5-11ea-8145-e1c27b08b220.gif)

**Comment by DominiqueMakowski** [comment]
@sbalci that sounds fantastic! However, please do note that report is in the process of refactoring with the goal of having it finally fixed, working, stable and more powerful than ever. 

I suggest we keep this thread open so that we can discuss and help fix any bugs/issues that would appear ☺️

**Comment by strengejacke** [comment]
From a legal point of view, as long as you don't violate any license issues (and as far as I can see, you don't), there's no hindrance to use the _report_ package.

But anyway, thanks for asking. :-) I'd say yes, please use the package if it's helpful for you! It's great to see that our packages are useful and used. However, you should know that report is currently really not close to "stable", as many packages which are required for report are under heavy development, and none of the api's is really stable currently. Thus, it's likely that you encounter issues unless we have released a first, "stable" CRAN version.

**Comment by sbalci** [comment]
Thank you very much.
I hope it will be helpful.
I am closely following easystats project and packages, and think to include more functions.
Best wishes.

**Comment by sbalci** [comment]
I have built the module and submitted to jamovi. But since it has many dependencies the module size is big that is why it is not currently included in the jamovi library. It can be installed install using side-load. Thank you very much for your support. 

windows: https://library.jamovi.org/win64/R3.6.1/ClinicoPath-0.0.1.jmo
macOS: https://library.jamovi.org/macos/R3.6.1/ClinicoPath-0.0.1.jmo
https://sbalci.github.io/ClinicoPathJamoviModule/reference/figures/jamovi-sideload.gif
Details: https://sbalci.github.io/ClinicoPathJamoviModule/

**Comment by sbalci** [comment]
Hi,

Similar to report package natural language summaries, I have also tried to generate summary sentences from survival models. I wanted to share it here and ask for comments, since you labelled this issue as `what's your opinion`.

If you find them useful, I will try to format them as new report method.

Code here:
https://github.com/sbalci/ClinicoPathJamoviModule/blob/master/R/survival.b.R


<img width="642" alt="pairwise-survival-summary" src="https://user-images.githubusercontent.com/7208830/81602576-8a8c7780-93d5-11ea-9ff2-72419e490d85.png">


<img width="659" alt="survival-summary" src="https://user-images.githubusercontent.com/7208830/81602587-8eb89500-93d5-11ea-831f-12928be29d0b.png">

**Comment by IndrajeetPatil** [comment]
Thanks, @sbalci, for your interest! Others have already chimed in, so closing this for now.

Please feel free to implement a wrapper for `jamovi`, and also to make a pull-request to add a method for reporting outputs from survival analysis.
