### ISSUE TITLE
report_participants() to verbose?

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#66]
``` r
library(report)
data <- data.frame(
  "Age" = c(22, 23, 54, 21, 8, 42),
  "Sex" = c("F", "F", "M", "M", "M", "F")
)

report_participants(data)
#> [1] "6 participants (Mean age = 28.33, Mean = 28.33, SD = 16.62, Median = 22.50, MAD = 11.86, range: [8, 54], Skewness = 0.67, Kurtosis = -0.97; 50.00% females)"
```

<sup>Created on 2020-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

1) Mean is mentioned twice.
2) I think, if median is already reported, we don't need MAD for "age". mean/sd is enough, maybe also median, but not mad.
3) Range is OK, but I never ever saw any paper where kurtosis and skewness of age was shown, at least not for a descriptive statistic.

**Comment by DominiqueMakowski** [comment]
Clearly too verbose, related I think to the fact that the default output from report.data.frame changed

**Comment by strengejacke** [comment]
I just saw this issue is resolved...

``` r
library(report)
data <- data.frame(
  "Age" = c(22, 23, 54, 21, 8, 42),
  "Sex" = c("F", "F", "M", "M", "M", "F")
)

report_participants(data)
#> [1] "6 participants (Mean age = 28.33, SD = 16.62, range = [8, 54]; 50.00% females)"
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
