### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#69]
We must think about how we name "beta", "b", "std. beta" etc., see https://github.com/easystats/report/issues/67

**Comment by DominiqueMakowski** [comment]
- frequentist regression coefficients candidates:
  - estimate
  - coefficient
  - b 
  - beta
  - ...

**Comment by strengejacke** [comment]
https://www.statisticshowto.datasciencecentral.com/standardized-beta-coefficient/
