### ISSUE TITLE
Reinforcement Learning in R

### ISSUE THREAD

**Issue by Anis-Hoayek** [easystats/report#75]
I learned the Reinforcement Learning package in R based on the document published on the following link : https://cran.r-project.org/web/packages/ReinforcementLearning/vignettes/ReinforcementLearning.html

The problem is the following: after performing a reinforcement learning on the “TIC TAC TOE” data (as suggested by the package authors), I tried to use the model to predict the next action of the following state “"XBXBB..X."
Logically the best next action should be “c6”, however the model is suggesting “c1” which is totally illogical because case “c1” has already an input X.
I will be thankful if someone may explain this strange situation.

**Comment by strengejacke** [comment]
Can you elaborate a bit more what your issue is, in particular related to the _report_ package?

**Comment by Anis-Hoayek** [comment]
I am runnung the following code trying to learn TIC TAC TOE game using reinforcement learning approach:

`library(devtools)
library(ReinforcementLearning)
# Load dataset
data("tictactoe")
head(tictactoe, 10)

# Define reinforcement learning parameters
control <- list(alpha = 0.2, gamma = 0.4, epsilon = 0.1)

# Perform reinforcement learning
model <- ReinforcementLearning(tictactoe, s = "State", a = "Action", r = "Reward", 
                               s_new = "NextState", iter = 1, control = control)

# Calculate optimal policy
pol <- computePolicy(model)

OptimalAction <- predict(model, "XBXBB..X.")`

In the last line, after training my algoritnm, I tried to predict the next action of the state "XBXBB..X." ("B" stands for 0 and "." for empty case in TIC TAC TOE).
logically the algorithm should return "c6" (i.e. the next "X" should be in case 6) but the output is "c1" which is completely illogical because the case "c1" has already an input "X"

**Comment by DominiqueMakowski** [comment]
I am sorry @Anis-Hoayek but that seems like it's unrelated to this package.

You can try posting your issue on the relevant package page: https://github.com/nproellochs/ReinforcementLearning
