### ISSUE TITLE
Unable to install reports

### ISSUE THREAD

**Issue by roschirosch** [easystats/report#76]
**Question and context**
Hi! I'm an R noob and would like to use the reports package.

I tried the following:

`devtools::install_github("easystats/report")
library(report)`

This produces the following output:

`> devtools::install_github("easystats/report")
Downloading GitHub repo easystats/report@master
These packages have more recent versions available.
Which would you like to update?

1:   numDeriv (2016.8-1 -> 2016.8-1.1) [CRAN]
2:   plyr     (1.8.4    -> 1.8.6     ) [CRAN]
3:   Rcpp     (1.0.0    -> 1.0.4     ) [CRAN]
4:   xtable   (1.8-3    -> 1.8-4     ) [CRAN]
5:   CRAN packages only
6:   All
7:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 6
mvtnorm     (NA       -> 1.1-0       ) [CRAN]
numDeriv    (2016.8-1 -> 2016.8-1.1  ) [CRAN]
performance (NA       -> 0.4.4       ) [CRAN]
plyr        (1.8.4    -> 1.8.6       ) [CRAN]
Rcpp        (1.0.0    -> 1.0.4       ) [CRAN]
xtable      (1.8-3    -> 1.8-4       ) [CRAN]
parameters  (NA       -> 826ffd7e3...) [GitHub]
modelbased  (NA       -> 76c282173...) [GitHub]
effectsize  (NA       -> 4595b4cfb...) [GitHub]
Installing 6 packages: mvtnorm, numDeriv, performance, plyr, Rcpp, xtable
Installing packages into ‘C:/Users/Anwender/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/mvtnorm_1.1-0.zip'
Content type 'application/zip' length 269554 bytes (263 KB)
downloaded 263 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/numDeriv_2016.8-1.1.zip'
Content type 'application/zip' length 115714 bytes (113 KB)
downloaded 113 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/performance_0.4.4.zip'
Content type 'application/zip' length 1348102 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/plyr_1.8.6.zip'
Content type 'application/zip' length 1311955 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/Rcpp_1.0.4.zip'
Content type 'application/zip' length 3046976 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/xtable_1.8-4.zip'
Content type 'application/zip' length 704805 bytes (688 KB)
downloaded 688 KB

package ‘mvtnorm’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘mvtnorm’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library(report)
Error in library(report) : there is no package called ‘report’`

I'm not sure what the differnce is, but I also tried `devtools::install_github("neuropsychology/report")`. The result was the same (i.e., there is no package called ‘report’).

I would be really greatful if someone could guide me :)

**Comment by strengejacke** [comment]
1. update packages from CRAN, make sure you have the _easystats_ packages installed (insight, bayestestR, effectsize, parameters, ...).
2) Use option `none` when asked to update other packages

or wait just a short time, we're now aiming at an initial release on CRAN...
