### ISSUE TITLE
could not find function "table_short"

### ISSUE THREAD

**Issue by drcanak** [easystats/report#78]
**Describe the bug**

From here:

https://github.com/easystats/report

This works wonderfully:

lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>% 
  report()

This does not:

lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>% 
  report() %>% 
  table_short()

Error in table_short(.) : could not find function "table_short"

All four of the functions table_short(), table_long(), text_short(), text_long() all seem to throw the same type of error.

**To Reproduce**

lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>% 
  report() %>% 
  table_short()

**Expected behaviour**

A table.

**Specifiations (please complete the following information):**
 - Package Version 0.1.0

**Comment by strengejacke** [comment]
Should be resolved meanwhile...

``` r
library(report)
library(magrittr)
lm(Sepal.Length ~ Petal.Length + Species, data=iris) %>%
  report() %>%
  table_short()
#> Parameter         | Coefficient |        p | Std_Coefficient |  Fit
#> -------------------------------------------------------------------
#> (Intercept)       |        3.68 | 1.97e-72 |            1.50 |     
#> Petal.Length      |        0.90 | 1.12e-28 |            1.93 |     
#> Speciesversicolor |       -1.60 | 7.37e-14 |           -1.93 |     
#> Speciesvirginica  |       -2.12 | 1.48e-12 |           -2.56 |     
#>                   |             |          |                 |     
#> R2                |             |          |                 | 0.84
#> R2 (adj.)         |             |          |                 | 0.83
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
