### ISSUE TITLE
correlation result (P value) was not comparable to other r package or other software

### ISSUE THREAD

**Issue by iaskmore** [easystats/report#80]
**Question and context**
When using correlation package from easystats to make analysis,
I found I could not get the same or similar P value results but a similar coef compared with basic commands (cor.test) or jasp (other open source software or spss).
I am not sure what happened to my result.

For example,
In cor.test 
variable a - variable b  P value was 0.0066;
In JASP
variable a - variable b  P value was 0.007;
In spss
variable a - variable b  P value was 0.007;

But  in easystats
the p-value was 0.312

I can share my data with the people via email.

thanks in advance.

**Comment by humanfactors** [comment]
Can you please share a reproducible example here via https://github.com/tidyverse/reprex.

I'm not having any issues, see below:

```
> correlation::cor_test(cars, "speed", "dist") Parameter1 \| Parameter2 \|    r \|    t \| df \|      p \|       95% CI \|  Method \| n_Obs ------------------------------------------------------------------------------------ speed      \|       dist \| 0.81 \| 9.46 \| 48 \| < .001 \| [0.68, 0.89] \| Pearson \|    50 > cor(cars$speed, cars$dist) [1] 0.8068949
```

Also if this is an issue with correlation package please open there. Cheers.
