### ISSUE TITLE
Documentation: r or d?

### ISSUE THREAD

**Issue by GegznaV** [easystats/report#81]
On https://easystats.github.io/report/articles/interpret_metrics.html#standardized-difference-d-cohens-d shouldn't it be **d**?
![image](https://user-images.githubusercontent.com/12725868/80250211-09667e00-867c-11ea-90ca-33003d0751c3.png)

**Comment by strengejacke** [comment]
@DominiqueMakowski This is your task ;-)

**Comment by DominiqueMakowski** [comment]
Yes it is correct (apologies for somehow missing this issue). However, this vignette has now been moved to effectsize hehe: https://github.com/easystats/effectsize/blob/master/vignettes/interpret.Rmd 👉  @mattansb

**Comment by DominiqueMakowski** [comment]
Though it is true that we might want to consider which place for its is better... maybe it should be in report?

**Comment by mattansb** [comment]
Funder (2019) don't actually offer rules for Cohen's d - they offer rules for *r*, and @DominiqueMakowski was using `d_to_r`... 
I think I'll remove this `funder2019` and replace with `cohen1988`, which is what most ppl expect anyway.
