### ISSUE TITLE
t-test reporting repeats with wrong d-values

### ISSUE THREAD

**Issue by LukasWallrich** [easystats/report#85]
**Describe the bug**
Running the t-test example from the documentation yields four result sentences - once with the correct d and then with three others, apparently taken from the 95% CI.

**To Reproduce**
 t.test(Sepal.Length ~ Species, data = iris[1:100, ]) %>% report(model) (see below for output)

**Expected behaviour**
Just the first sentence should be returned, rather than the four that I get.

**Specifiations (please complete the following information):**
 - Package Version [e.g. 0.1.0]

**Wrong output**

`The Welch Two Sample t-test suggests that the difference of Sepal.Length by Species (mean in group setosa = 5.01, mean in group versicolor = 5.94) is significant (difference = -0.93, 95% CI [-1.11, -0.75], t(86.54) = -10.52, p < .001) and can be considered as very large (Cohen's d = -2.26)., The Welch Two Sample t-test suggests that the difference of Sepal.Length by Species (mean in group setosa = 5.01, mean in group versicolor = 5.94) is significant (difference = -0.93, 95% CI [-1.11, -0.75], t(86.54) = -10.52, p < .001) and can be considered as very large (Cohen's d = 0.95)., The Welch Two Sample t-test suggests that the difference of Sepal.Length by Species (mean in group setosa = 5.01, mean in group versicolor = 5.94) is significant (difference = -0.93, 95% CI [-1.11, -0.75], t(86.54) = -10.52, p < .001) and can be considered as very large (Cohen's d = -2.80). and The Welch Two Sample t-test suggests that the difference of Sepal.Length by Species (mean in group setosa = 5.01, mean in group versicolor = 5.94) is significant (difference = -0.93, 95% CI [-1.11, -0.75], t(86.54) = -10.52, p < .001) and can be considered as very large (Cohen's d = -1.72).`

**Comment by DominiqueMakowski** [comment]
Should be fixed now (on the master branch) let me know!
