### ISSUE TITLE
report for lmer mixed effects model with no fixed effects has some minor bugs

### ISSUE THREAD

**Issue by jrosen48** [easystats/report#88]
**Describe the bug**
The report for `lme4::lmer()` mixed effects model with no fixed effects has some minor bugs. Namely, the report is written as if there are or should be fixed effects, but sometimes users may like to report a model only with random effects.

**To Reproduce**
``` r
library(report)
library(lme4)
#> Loading required package: Matrix

fm1 <- lmer(Reaction ~ 1 + (1 | Subject), sleepstudy)
report(fm1)
#> We fitted a linear mixed model (estimated using REML and nloptwrap optimizer) to predict Reaction with  (formula = Reaction ~ 1). The model included Subject as random effects (formula = ~1 | Subject). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. Effect sizes were labelled following Funder's (2019) recommendations.The model's total explanatory power is substantial (conditional R2 = 0.39) and the part related to the fixed effects alone (marginal R2) is of 0.00. The model's intercept, corresponding to , is at 298.51 (SE = 9.05, 95% CI [280.77, 316.25], p < .001). Within this model:
#> 
#>   -  is  and can be considered as very large and not significant (beta = , SE = , std. beta = , p ).
```

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Expected behaviour**
I think that the line reporting the fixed effects should be removed entirely.

**Comment by DominiqueMakowski** [comment]
Indeed, thanks for reporting the bug! Will try to give it a look soon ☺️

**Comment by strengejacke** [comment]
We have `insight::is_nullmodel()` and can check such exceptions.
