### ISSUE TITLE
equivalence-testing

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#9]
Similar to `equivalence_test()` in bayestestR, we might think about implementing a similar method for the frequentists framework. See this paper: https://doi.org/10.1371/journal.pone.0195145

Not sure if report, or better performance might be the package for such a function?

**Comment by DominiqueMakowski** [comment]
Very interesting indeed! If I understood correctly, this "test" would mainly apply on parameters of the model, hence it should be located there? In general, I would like to keep `report` free of any actual computations, leaving it to be "just" (it's already quite a reasonable amount of code ^^) a wrapper for these.
