### ISSUE TITLE
Function .format_big_small()?

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#90]
@DominiqueMakowski the function `.format_big_small()` in https://github.com/easystats/report/blob/master/R/report.bayestestR.R no longer exists. What was it suppose to do?

```r
  #### table ####
  model$Model <- paste0(" [", seq_len(nrow(model)), "] ", model$Model)
  bf_table <- as.data.frame(model)
  bf_table$BF <- bayestestR:::.format_big_small(model$BF, ...)
  colnames(bf_table) <- c("Model", "Bayes factor")


  table_footer <- matrix(rep("", 6), nrow = 3)
  table_footer[2, 1] <- paste0("Bayes Factor Type: ", BF_method)
  table_footer[3, 1] <- paste0("Against denominator - model ", denominator)
  colnames(table_footer) <- colnames(bf_table)
  bf_table <- rbind(bf_table, table_footer)
```

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
please fix soon, so we can run tests...

**Comment by DominiqueMakowski** [comment]
@mattansb If I remember correctly this was to accommodate the level of precision and print like `> 300` if the BF was too high right?

**Comment by mattansb** [comment]
This was originally to accommodate printing of ratios, that can be very large / small.
This functionality has now been transferred to to `insight::format_value()`:

``` r
x <- 10 ^ seq(-5, 5)
insight::format_value(x)
#>  [1] "1.00e-05" "1.00e-04" "0.00"     "0.01"     "0.10"     "1.00"    
#>  [7] "10.00"    "100.00"   "1000.00"  "10000.00" "1.00e+05"
```

<sup>Created on 2020-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Actually, we have also `format_bf()`.

**Comment by mattansb** [comment]
Hmm... format_bf doesn't deal well with small values. I will give it an upgrade (:

**Comment by strengejacke** [comment]
```r
insight::format_bf(0.000001)
#> "BF = 1.00e-06"
```

**Comment by mattansb** [comment]
Should `protect_ratio = TRUE` be added here too?

**Comment by strengejacke** [comment]
Yes, I'd say so... even if this option is not available yet...

**Comment by DominiqueMakowski** [comment]
Should we print something like  `< 0.001` if very the BF is very smol?

**Comment by mattansb** [comment]
Yup (:
