### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#93]
@DominiqueMakowski we should revise / remove this paragraph in the readme:
https://github.com/easystats/report#supported-packages

Actually, _report_ now supports much more models.

**Comment by DominiqueMakowski** [comment]
Yes I agree we should remove it because the endgoal indeed is for it to be tied to the support list of parameters / performance / effectsize

(and thanks a ton for nailing all of that down 👑)

**Comment by strengejacke** [comment]
I think report is in shape for initial submission. We must look if the there are no check issues, and then there's probably not much left to do.

Anything you'd like to address before submission?

**Comment by DominiqueMakowski** [comment]
what do you think about the API? The methods names, the defaults, and the general flow and feeling?

**Comment by strengejacke** [comment]
I think the API and methods names are OK. We use the argument names we used in other functions, so report is consistent with other easystats packages. I think general flow and feeling can be judged better once we have the "stable" version running and  using for some time, but I don't see any "flaws" or inconsistencies right now...

**Comment by strengejacke** [comment]
@DominiqueMakowski this is a somewhat "radical" change, but I removed the `median` argument from `report.data.frame()` and alike, to be more consistent with the `centrality` argument we use in _bayestestR_ and other easystats-packages. This means, that you _have_ to specify a centrality value if you _want_ to report dispersion indices (formerly, you could return SD or MAD without returning the mean or median). I think this is no big problem, as you typically want the centrality as well if you request dispersion, and it's consistent with our API from other packages.

**Comment by DominiqueMakowski** [comment]
yes the median arg was a relic from ancient times

**Comment by strengejacke** [comment]
had to adopt `report_participants()`, but tests pass, all seems to be OK. :-)
