### ISSUE TITLE
Docs that need to be revised for submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#96]
Who would like to address this? 🥰  Mostly, the return value is missing.

- [x] https://easystats.github.io/report/reference/text_long.html
- [x] https://easystats.github.io/report/reference/as.report.html
- [x] https://easystats.github.io/report/reference/format_algorithm.html (return value)
- [x] https://easystats.github.io/report/reference/format_model.html (return value)
- [x] https://easystats.github.io/report/reference/format_text.html (return value)
- [x] https://easystats.github.io/report/reference/model_table.html (return value)
- [x] https://easystats.github.io/report/reference/model_text.html (return value)
- [x] https://easystats.github.io/report/reference/rename_if_possible.html (return value)
- [x] https://easystats.github.io/report/reference/report.html (return value)
- [x] https://easystats.github.io/report/reference/report.aov.html (return value, link in "see also")
- [x] https://easystats.github.io/report/reference/report.bayesfactor_models.html (return value, link in "see also")
- [x] https://easystats.github.io/report/reference/report.data.frame.html (return value, link in "see also")
- [x] https://easystats.github.io/report/reference/report.htest.html (return value, link in "see also")
- [x] https://easystats.github.io/report/reference/report.lm.html (return value)
- [x] https://easystats.github.io/report/reference/report.lmerMod.html (return value)
- [x] https://easystats.github.io/report/reference/report.stanreg.html (return value)
- [x] https://easystats.github.io/report/reference/report_model.html (return value, link in "see also")
- [x] https://easystats.github.io/report/reference/report_participants.html (return value)
- [x] https://easystats.github.io/report/reference/report_sample.html (return value)
- [x] https://easystats.github.io/report/reference/show_packages.html (return value)

For `model_text()` and `model_table()`, I would also link to `report()`, which describes the arguments in detail.

**Comment by mattansb** [comment]
Isn't the returned value of all of the `report()` methods the same?

```R
@inherit foo return
```

**Comment by strengejacke** [comment]
Yes, for `report.<class>()`, it's the same.

**Comment by strengejacke** [comment]
How can you inherit return values? `@inherit report return`?

**Comment by mattansb** [comment]
Yeah, `@inherit function_name return`

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
@DominiqueMakowski could you add the docs for `table_short()`? (or `text_long()`, it's the same file / docs anyway, so I'm referring to the first bullet point above)

**Comment by DominiqueMakowski** [comment]
yup will do

**Comment by strengejacke** [comment]
and `as.report()`, please. All other docs should be revised now.

**Comment by strengejacke** [comment]
Also, in this example: https://easystats.github.io/report/reference/report.data.frame.html

There is `summary(as.data.frame())`, which makes no sense in the example, I'd say, or not?

**Comment by DominiqueMakowski** [comment]
> There is summary(as.data.frame()), which makes no sense in the example, I'd say, or not?

It should have been the equivalent of `table_short()`..

But it's quite confusing I realize that there are different APIs sprinkled throughout the examples 😅

**Comment by strengejacke** [comment]
> > There is summary(as.data.frame()), which makes no sense in the example, I'd say, or not?
> 
> It should have been the equivalent of `table_short()`..
> 
> But it's quite confusing I realize that there are different APIs sprinkled throughout the examples 😅

No, it's not confusing regarding the API, it just gives the usual summary on a data frame, and no "report" (look at the examples from the above linked page). That was what I meant ;-)

**Comment by strengejacke** [comment]
From the example:

``` r
library(report)
r <- report(iris, centrality = "median", dispersion = FALSE,
            distribution = TRUE, missing_percentage = TRUE)
summary(as.data.frame(r))
#>    Variable                Level       n_Obs            Mean      
#>  Length:7           setosa    :1   Min.   : 50.0   Min.   :1.199  
#>  Class :character   versicolor:1   1st Qu.: 50.0   1st Qu.:2.593  
#>  Mode  :character   virginica :1   Median :150.0   Median :3.408  
#>                     NA's      :4   Mean   :107.1   Mean   :3.465  
#>                                    3rd Qu.:150.0   3rd Qu.:4.279  
#>                                    Max.   :150.0   Max.   :5.843  
#>                                                    NA's   :3      
#>        SD             Median           MAD              Min       
#>  Min.   :0.4359   Min.   :1.300   Min.   :0.4448   Min.   :0.100  
#>  1st Qu.:0.6806   1st Qu.:2.575   1st Qu.:0.8896   1st Qu.:0.775  
#>  Median :0.7952   Median :3.675   Median :1.0378   Median :1.500  
#>  Mean   :0.9479   Mean   :3.612   Mean   :1.0934   Mean   :1.850  
#>  3rd Qu.:1.0624   3rd Qu.:4.713   3rd Qu.:1.2417   3rd Qu.:2.575  
#>  Max.   :1.7653   Max.   :5.800   Max.   :1.8533   Max.   :4.300  
#>  NA's   :3        NA's   :3       NA's   :3        NA's   :3      
#>       Max           Skewness           Kurtosis       percentage_Missing
#>  Min.   :2.500   Min.   :-0.27488   Min.   :-1.3955   Min.   :0         
#>  1st Qu.:3.925   1st Qu.:-0.14595   1st Qu.:-1.3509   1st Qu.:0         
#>  Median :5.650   Median : 0.10597   Median :-0.9548   Median :0         
#>  Mean   :5.425   Mean   : 0.06401   Mean   :-0.7810   Mean   :0         
#>  3rd Qu.:7.150   3rd Qu.: 0.31592   3rd Qu.:-0.3849   3rd Qu.:0         
#>  Max.   :7.900   Max.   : 0.31897   Max.   : 0.1810   Max.   :0         
#>  NA's   :3       NA's   :3          NA's   :3         NA's   :3         
#>  percentage_Obs 
#>  Min.   :33.33  
#>  1st Qu.:33.33  
#>  Median :33.33  
#>  Mean   :33.33  
#>  3rd Qu.:33.33  
#>  Max.   :33.33  
#>  NA's   :4
```

<sup>Created on 2020-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
